package org.fao.fir.cgrfa.dao.mapper.model;

public class ControlledlistsPkey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ControlledLists_pkey.pk
     *
     * @mbggenerated Thu May 14 12:52:48 CEST 2015
     */
    private Integer pk;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ControlledLists_pkey.pk
     *
     * @return the value of public.ControlledLists_pkey.pk
     *
     * @mbggenerated Thu May 14 12:52:48 CEST 2015
     */
    public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ControlledLists_pkey.pk
     *
     * @param pk the value for public.ControlledLists_pkey.pk
     *
     * @mbggenerated Thu May 14 12:52:48 CEST 2015
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }
}