package org.fao.fir.cgrfa.dao.mapper.model;

public class CountriesInfoNew {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Countries_info_new.UnCode
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private Integer uncode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Countries_info_new.Use
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private String use;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Countries_info_new.Cgrfa
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private Integer cgrfa;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Countries_info_new.Faostat
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private Integer faostat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Countries_info_new.Figis
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private Integer figis;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Countries_info_new.Name
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Countries_info_new.Iso3
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private String iso3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Countries_info_new.Position
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private Integer position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Countries_info_new.Language
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private String language;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Countries_info_new.ClassType
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private Integer classtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Countries_info_new.FishstatJ
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private Integer fishstatj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Countries_info_new.Geographic
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private Integer geographic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Countries_info_new.Region
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private Integer region;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Countries_info_new.Economic
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private Integer economic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Countries_info_new.Industrial
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private String industrial;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Countries_info_new.LowIncome
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private String lowincome;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Countries_info_new.English
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private String english;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Countries_info_new.French
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private String french;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Countries_info_new.Spanish
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private String spanish;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Countries_info_new.UnCode
     *
     * @return the value of public.Countries_info_new.UnCode
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public Integer getUncode() {
        return uncode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Countries_info_new.UnCode
     *
     * @param uncode the value for public.Countries_info_new.UnCode
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setUncode(Integer uncode) {
        this.uncode = uncode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Countries_info_new.Use
     *
     * @return the value of public.Countries_info_new.Use
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public String getUse() {
        return use;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Countries_info_new.Use
     *
     * @param use the value for public.Countries_info_new.Use
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setUse(String use) {
        this.use = use == null ? null : use.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Countries_info_new.Cgrfa
     *
     * @return the value of public.Countries_info_new.Cgrfa
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public Integer getCgrfa() {
        return cgrfa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Countries_info_new.Cgrfa
     *
     * @param cgrfa the value for public.Countries_info_new.Cgrfa
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setCgrfa(Integer cgrfa) {
        this.cgrfa = cgrfa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Countries_info_new.Faostat
     *
     * @return the value of public.Countries_info_new.Faostat
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public Integer getFaostat() {
        return faostat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Countries_info_new.Faostat
     *
     * @param faostat the value for public.Countries_info_new.Faostat
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setFaostat(Integer faostat) {
        this.faostat = faostat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Countries_info_new.Figis
     *
     * @return the value of public.Countries_info_new.Figis
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public Integer getFigis() {
        return figis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Countries_info_new.Figis
     *
     * @param figis the value for public.Countries_info_new.Figis
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setFigis(Integer figis) {
        this.figis = figis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Countries_info_new.Name
     *
     * @return the value of public.Countries_info_new.Name
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Countries_info_new.Name
     *
     * @param name the value for public.Countries_info_new.Name
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Countries_info_new.Iso3
     *
     * @return the value of public.Countries_info_new.Iso3
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public String getIso3() {
        return iso3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Countries_info_new.Iso3
     *
     * @param iso3 the value for public.Countries_info_new.Iso3
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setIso3(String iso3) {
        this.iso3 = iso3 == null ? null : iso3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Countries_info_new.Position
     *
     * @return the value of public.Countries_info_new.Position
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public Integer getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Countries_info_new.Position
     *
     * @param position the value for public.Countries_info_new.Position
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setPosition(Integer position) {
        this.position = position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Countries_info_new.Language
     *
     * @return the value of public.Countries_info_new.Language
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public String getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Countries_info_new.Language
     *
     * @param language the value for public.Countries_info_new.Language
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setLanguage(String language) {
        this.language = language == null ? null : language.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Countries_info_new.ClassType
     *
     * @return the value of public.Countries_info_new.ClassType
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public Integer getClasstype() {
        return classtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Countries_info_new.ClassType
     *
     * @param classtype the value for public.Countries_info_new.ClassType
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setClasstype(Integer classtype) {
        this.classtype = classtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Countries_info_new.FishstatJ
     *
     * @return the value of public.Countries_info_new.FishstatJ
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public Integer getFishstatj() {
        return fishstatj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Countries_info_new.FishstatJ
     *
     * @param fishstatj the value for public.Countries_info_new.FishstatJ
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setFishstatj(Integer fishstatj) {
        this.fishstatj = fishstatj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Countries_info_new.Geographic
     *
     * @return the value of public.Countries_info_new.Geographic
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public Integer getGeographic() {
        return geographic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Countries_info_new.Geographic
     *
     * @param geographic the value for public.Countries_info_new.Geographic
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setGeographic(Integer geographic) {
        this.geographic = geographic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Countries_info_new.Region
     *
     * @return the value of public.Countries_info_new.Region
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public Integer getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Countries_info_new.Region
     *
     * @param region the value for public.Countries_info_new.Region
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setRegion(Integer region) {
        this.region = region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Countries_info_new.Economic
     *
     * @return the value of public.Countries_info_new.Economic
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public Integer getEconomic() {
        return economic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Countries_info_new.Economic
     *
     * @param economic the value for public.Countries_info_new.Economic
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setEconomic(Integer economic) {
        this.economic = economic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Countries_info_new.Industrial
     *
     * @return the value of public.Countries_info_new.Industrial
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public String getIndustrial() {
        return industrial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Countries_info_new.Industrial
     *
     * @param industrial the value for public.Countries_info_new.Industrial
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setIndustrial(String industrial) {
        this.industrial = industrial == null ? null : industrial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Countries_info_new.LowIncome
     *
     * @return the value of public.Countries_info_new.LowIncome
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public String getLowincome() {
        return lowincome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Countries_info_new.LowIncome
     *
     * @param lowincome the value for public.Countries_info_new.LowIncome
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setLowincome(String lowincome) {
        this.lowincome = lowincome == null ? null : lowincome.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Countries_info_new.English
     *
     * @return the value of public.Countries_info_new.English
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public String getEnglish() {
        return english;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Countries_info_new.English
     *
     * @param english the value for public.Countries_info_new.English
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setEnglish(String english) {
        this.english = english == null ? null : english.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Countries_info_new.French
     *
     * @return the value of public.Countries_info_new.French
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public String getFrench() {
        return french;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Countries_info_new.French
     *
     * @param french the value for public.Countries_info_new.French
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setFrench(String french) {
        this.french = french == null ? null : french.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Countries_info_new.Spanish
     *
     * @return the value of public.Countries_info_new.Spanish
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public String getSpanish() {
        return spanish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Countries_info_new.Spanish
     *
     * @param spanish the value for public.Countries_info_new.Spanish
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setSpanish(String spanish) {
        this.spanish = spanish == null ? null : spanish.trim();
    }
}