package org.fao.fir.cgrfa.dao.mapper.model;

public class FieldlabelKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.FieldLabel.name
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.FieldLabel.row_id
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private Integer rowId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.FieldLabel.name
     *
     * @return the value of public.FieldLabel.name
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.FieldLabel.name
     *
     * @param name the value for public.FieldLabel.name
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.FieldLabel.row_id
     *
     * @return the value of public.FieldLabel.row_id
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public Integer getRowId() {
        return rowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.FieldLabel.row_id
     *
     * @param rowId the value for public.FieldLabel.row_id
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setRowId(Integer rowId) {
        this.rowId = rowId;
    }
}