package org.fao.fir.cgrfa.dao.mapper.model;

public class Fieldchecklist {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.FieldCheckList.name
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.FieldCheckList.type
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.FieldCheckList.cl_id
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private Integer clId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.FieldCheckList.ord
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private Integer ord;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.FieldCheckList.tab
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private Integer tab;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.FieldCheckList.name
     *
     * @return the value of public.FieldCheckList.name
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.FieldCheckList.name
     *
     * @param name the value for public.FieldCheckList.name
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.FieldCheckList.type
     *
     * @return the value of public.FieldCheckList.type
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.FieldCheckList.type
     *
     * @param type the value for public.FieldCheckList.type
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.FieldCheckList.cl_id
     *
     * @return the value of public.FieldCheckList.cl_id
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public Integer getClId() {
        return clId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.FieldCheckList.cl_id
     *
     * @param clId the value for public.FieldCheckList.cl_id
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setClId(Integer clId) {
        this.clId = clId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.FieldCheckList.ord
     *
     * @return the value of public.FieldCheckList.ord
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public Integer getOrd() {
        return ord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.FieldCheckList.ord
     *
     * @param ord the value for public.FieldCheckList.ord
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setOrd(Integer ord) {
        this.ord = ord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.FieldCheckList.tab
     *
     * @return the value of public.FieldCheckList.tab
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public Integer getTab() {
        return tab;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.FieldCheckList.tab
     *
     * @param tab the value for public.FieldCheckList.tab
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setTab(Integer tab) {
        this.tab = tab;
    }
}