package org.fao.fir.cgrfa.dao.mapper.model;

public class Fishstatj {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.FishstatJ.Code
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private Integer code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.FishstatJ.English
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private String english;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.FishstatJ.French
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private String french;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.FishstatJ.Spanish
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private String spanish;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.FishstatJ.Code
     *
     * @return the value of public.FishstatJ.Code
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public Integer getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.FishstatJ.Code
     *
     * @param code the value for public.FishstatJ.Code
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setCode(Integer code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.FishstatJ.English
     *
     * @return the value of public.FishstatJ.English
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public String getEnglish() {
        return english;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.FishstatJ.English
     *
     * @param english the value for public.FishstatJ.English
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setEnglish(String english) {
        this.english = english == null ? null : english.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.FishstatJ.French
     *
     * @return the value of public.FishstatJ.French
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public String getFrench() {
        return french;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.FishstatJ.French
     *
     * @param french the value for public.FishstatJ.French
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setFrench(String french) {
        this.french = french == null ? null : french.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.FishstatJ.Spanish
     *
     * @return the value of public.FishstatJ.Spanish
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public String getSpanish() {
        return spanish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.FishstatJ.Spanish
     *
     * @param spanish the value for public.FishstatJ.Spanish
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setSpanish(String spanish) {
        this.spanish = spanish == null ? null : spanish.trim();
    }
}