package org.fao.fir.cgrfa.dao.mapper.model;

import java.util.ArrayList;
import java.util.List;

public class Question31Example {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.Question31
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.Question31
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.Question31
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question31
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public Question31Example() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question31
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question31
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question31
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question31
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question31
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question31
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question31
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question31
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question31
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question31
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.Question31
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRownumberIsNull() {
            addCriterion("rownumber is null");
            return (Criteria) this;
        }

        public Criteria andRownumberIsNotNull() {
            addCriterion("rownumber is not null");
            return (Criteria) this;
        }

        public Criteria andRownumberEqualTo(Integer value) {
            addCriterion("rownumber =", value, "rownumber");
            return (Criteria) this;
        }

        public Criteria andRownumberNotEqualTo(Integer value) {
            addCriterion("rownumber <>", value, "rownumber");
            return (Criteria) this;
        }

        public Criteria andRownumberGreaterThan(Integer value) {
            addCriterion("rownumber >", value, "rownumber");
            return (Criteria) this;
        }

        public Criteria andRownumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("rownumber >=", value, "rownumber");
            return (Criteria) this;
        }

        public Criteria andRownumberLessThan(Integer value) {
            addCriterion("rownumber <", value, "rownumber");
            return (Criteria) this;
        }

        public Criteria andRownumberLessThanOrEqualTo(Integer value) {
            addCriterion("rownumber <=", value, "rownumber");
            return (Criteria) this;
        }

        public Criteria andRownumberIn(List<Integer> values) {
            addCriterion("rownumber in", values, "rownumber");
            return (Criteria) this;
        }

        public Criteria andRownumberNotIn(List<Integer> values) {
            addCriterion("rownumber not in", values, "rownumber");
            return (Criteria) this;
        }

        public Criteria andRownumberBetween(Integer value1, Integer value2) {
            addCriterion("rownumber between", value1, value2, "rownumber");
            return (Criteria) this;
        }

        public Criteria andRownumberNotBetween(Integer value1, Integer value2) {
            addCriterion("rownumber not between", value1, value2, "rownumber");
            return (Criteria) this;
        }

        public Criteria andCountryIsNull() {
            addCriterion("country is null");
            return (Criteria) this;
        }

        public Criteria andCountryIsNotNull() {
            addCriterion("country is not null");
            return (Criteria) this;
        }

        public Criteria andCountryEqualTo(String value) {
            addCriterion("country =", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotEqualTo(String value) {
            addCriterion("country <>", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryGreaterThan(String value) {
            addCriterion("country >", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryGreaterThanOrEqualTo(String value) {
            addCriterion("country >=", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryLessThan(String value) {
            addCriterion("country <", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryLessThanOrEqualTo(String value) {
            addCriterion("country <=", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryLike(String value) {
            addCriterion("country like", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotLike(String value) {
            addCriterion("country not like", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryIn(List<String> values) {
            addCriterion("country in", values, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotIn(List<String> values) {
            addCriterion("country not in", values, "country");
            return (Criteria) this;
        }

        public Criteria andCountryBetween(String value1, String value2) {
            addCriterion("country between", value1, value2, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotBetween(String value1, String value2) {
            addCriterion("country not between", value1, value2, "country");
            return (Criteria) this;
        }

        public Criteria andRegionIsNull() {
            addCriterion("region is null");
            return (Criteria) this;
        }

        public Criteria andRegionIsNotNull() {
            addCriterion("region is not null");
            return (Criteria) this;
        }

        public Criteria andRegionEqualTo(String value) {
            addCriterion("region =", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionNotEqualTo(String value) {
            addCriterion("region <>", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionGreaterThan(String value) {
            addCriterion("region >", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionGreaterThanOrEqualTo(String value) {
            addCriterion("region >=", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionLessThan(String value) {
            addCriterion("region <", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionLessThanOrEqualTo(String value) {
            addCriterion("region <=", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionLike(String value) {
            addCriterion("region like", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionNotLike(String value) {
            addCriterion("region not like", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionIn(List<String> values) {
            addCriterion("region in", values, "region");
            return (Criteria) this;
        }

        public Criteria andRegionNotIn(List<String> values) {
            addCriterion("region not in", values, "region");
            return (Criteria) this;
        }

        public Criteria andRegionBetween(String value1, String value2) {
            addCriterion("region between", value1, value2, "region");
            return (Criteria) this;
        }

        public Criteria andRegionNotBetween(String value1, String value2) {
            addCriterion("region not between", value1, value2, "region");
            return (Criteria) this;
        }

        public Criteria andGeographicRegionIsNull() {
            addCriterion("geographic_region is null");
            return (Criteria) this;
        }

        public Criteria andGeographicRegionIsNotNull() {
            addCriterion("geographic_region is not null");
            return (Criteria) this;
        }

        public Criteria andGeographicRegionEqualTo(String value) {
            addCriterion("geographic_region =", value, "geographicRegion");
            return (Criteria) this;
        }

        public Criteria andGeographicRegionNotEqualTo(String value) {
            addCriterion("geographic_region <>", value, "geographicRegion");
            return (Criteria) this;
        }

        public Criteria andGeographicRegionGreaterThan(String value) {
            addCriterion("geographic_region >", value, "geographicRegion");
            return (Criteria) this;
        }

        public Criteria andGeographicRegionGreaterThanOrEqualTo(String value) {
            addCriterion("geographic_region >=", value, "geographicRegion");
            return (Criteria) this;
        }

        public Criteria andGeographicRegionLessThan(String value) {
            addCriterion("geographic_region <", value, "geographicRegion");
            return (Criteria) this;
        }

        public Criteria andGeographicRegionLessThanOrEqualTo(String value) {
            addCriterion("geographic_region <=", value, "geographicRegion");
            return (Criteria) this;
        }

        public Criteria andGeographicRegionLike(String value) {
            addCriterion("geographic_region like", value, "geographicRegion");
            return (Criteria) this;
        }

        public Criteria andGeographicRegionNotLike(String value) {
            addCriterion("geographic_region not like", value, "geographicRegion");
            return (Criteria) this;
        }

        public Criteria andGeographicRegionIn(List<String> values) {
            addCriterion("geographic_region in", values, "geographicRegion");
            return (Criteria) this;
        }

        public Criteria andGeographicRegionNotIn(List<String> values) {
            addCriterion("geographic_region not in", values, "geographicRegion");
            return (Criteria) this;
        }

        public Criteria andGeographicRegionBetween(String value1, String value2) {
            addCriterion("geographic_region between", value1, value2, "geographicRegion");
            return (Criteria) this;
        }

        public Criteria andGeographicRegionNotBetween(String value1, String value2) {
            addCriterion("geographic_region not between", value1, value2, "geographicRegion");
            return (Criteria) this;
        }

        public Criteria andEconomicRegionIsNull() {
            addCriterion("economic_region is null");
            return (Criteria) this;
        }

        public Criteria andEconomicRegionIsNotNull() {
            addCriterion("economic_region is not null");
            return (Criteria) this;
        }

        public Criteria andEconomicRegionEqualTo(String value) {
            addCriterion("economic_region =", value, "economicRegion");
            return (Criteria) this;
        }

        public Criteria andEconomicRegionNotEqualTo(String value) {
            addCriterion("economic_region <>", value, "economicRegion");
            return (Criteria) this;
        }

        public Criteria andEconomicRegionGreaterThan(String value) {
            addCriterion("economic_region >", value, "economicRegion");
            return (Criteria) this;
        }

        public Criteria andEconomicRegionGreaterThanOrEqualTo(String value) {
            addCriterion("economic_region >=", value, "economicRegion");
            return (Criteria) this;
        }

        public Criteria andEconomicRegionLessThan(String value) {
            addCriterion("economic_region <", value, "economicRegion");
            return (Criteria) this;
        }

        public Criteria andEconomicRegionLessThanOrEqualTo(String value) {
            addCriterion("economic_region <=", value, "economicRegion");
            return (Criteria) this;
        }

        public Criteria andEconomicRegionLike(String value) {
            addCriterion("economic_region like", value, "economicRegion");
            return (Criteria) this;
        }

        public Criteria andEconomicRegionNotLike(String value) {
            addCriterion("economic_region not like", value, "economicRegion");
            return (Criteria) this;
        }

        public Criteria andEconomicRegionIn(List<String> values) {
            addCriterion("economic_region in", values, "economicRegion");
            return (Criteria) this;
        }

        public Criteria andEconomicRegionNotIn(List<String> values) {
            addCriterion("economic_region not in", values, "economicRegion");
            return (Criteria) this;
        }

        public Criteria andEconomicRegionBetween(String value1, String value2) {
            addCriterion("economic_region between", value1, value2, "economicRegion");
            return (Criteria) this;
        }

        public Criteria andEconomicRegionNotBetween(String value1, String value2) {
            addCriterion("economic_region not between", value1, value2, "economicRegion");
            return (Criteria) this;
        }

        public Criteria andStakeholdersIsNull() {
            addCriterion("stakeholders is null");
            return (Criteria) this;
        }

        public Criteria andStakeholdersIsNotNull() {
            addCriterion("stakeholders is not null");
            return (Criteria) this;
        }

        public Criteria andStakeholdersEqualTo(String value) {
            addCriterion("stakeholders =", value, "stakeholders");
            return (Criteria) this;
        }

        public Criteria andStakeholdersNotEqualTo(String value) {
            addCriterion("stakeholders <>", value, "stakeholders");
            return (Criteria) this;
        }

        public Criteria andStakeholdersGreaterThan(String value) {
            addCriterion("stakeholders >", value, "stakeholders");
            return (Criteria) this;
        }

        public Criteria andStakeholdersGreaterThanOrEqualTo(String value) {
            addCriterion("stakeholders >=", value, "stakeholders");
            return (Criteria) this;
        }

        public Criteria andStakeholdersLessThan(String value) {
            addCriterion("stakeholders <", value, "stakeholders");
            return (Criteria) this;
        }

        public Criteria andStakeholdersLessThanOrEqualTo(String value) {
            addCriterion("stakeholders <=", value, "stakeholders");
            return (Criteria) this;
        }

        public Criteria andStakeholdersLike(String value) {
            addCriterion("stakeholders like", value, "stakeholders");
            return (Criteria) this;
        }

        public Criteria andStakeholdersNotLike(String value) {
            addCriterion("stakeholders not like", value, "stakeholders");
            return (Criteria) this;
        }

        public Criteria andStakeholdersIn(List<String> values) {
            addCriterion("stakeholders in", values, "stakeholders");
            return (Criteria) this;
        }

        public Criteria andStakeholdersNotIn(List<String> values) {
            addCriterion("stakeholders not in", values, "stakeholders");
            return (Criteria) this;
        }

        public Criteria andStakeholdersBetween(String value1, String value2) {
            addCriterion("stakeholders between", value1, value2, "stakeholders");
            return (Criteria) this;
        }

        public Criteria andStakeholdersNotBetween(String value1, String value2) {
            addCriterion("stakeholders not between", value1, value2, "stakeholders");
            return (Criteria) this;
        }

        public Criteria andRoleOfStakeholderInRegardsOfAqgrIsNull() {
            addCriterion("role_of_stakeholder_in_regards_of_aqgr is null");
            return (Criteria) this;
        }

        public Criteria andRoleOfStakeholderInRegardsOfAqgrIsNotNull() {
            addCriterion("role_of_stakeholder_in_regards_of_aqgr is not null");
            return (Criteria) this;
        }

        public Criteria andRoleOfStakeholderInRegardsOfAqgrEqualTo(String value) {
            addCriterion("role_of_stakeholder_in_regards_of_aqgr =", value, "roleOfStakeholderInRegardsOfAqgr");
            return (Criteria) this;
        }

        public Criteria andRoleOfStakeholderInRegardsOfAqgrNotEqualTo(String value) {
            addCriterion("role_of_stakeholder_in_regards_of_aqgr <>", value, "roleOfStakeholderInRegardsOfAqgr");
            return (Criteria) this;
        }

        public Criteria andRoleOfStakeholderInRegardsOfAqgrGreaterThan(String value) {
            addCriterion("role_of_stakeholder_in_regards_of_aqgr >", value, "roleOfStakeholderInRegardsOfAqgr");
            return (Criteria) this;
        }

        public Criteria andRoleOfStakeholderInRegardsOfAqgrGreaterThanOrEqualTo(String value) {
            addCriterion("role_of_stakeholder_in_regards_of_aqgr >=", value, "roleOfStakeholderInRegardsOfAqgr");
            return (Criteria) this;
        }

        public Criteria andRoleOfStakeholderInRegardsOfAqgrLessThan(String value) {
            addCriterion("role_of_stakeholder_in_regards_of_aqgr <", value, "roleOfStakeholderInRegardsOfAqgr");
            return (Criteria) this;
        }

        public Criteria andRoleOfStakeholderInRegardsOfAqgrLessThanOrEqualTo(String value) {
            addCriterion("role_of_stakeholder_in_regards_of_aqgr <=", value, "roleOfStakeholderInRegardsOfAqgr");
            return (Criteria) this;
        }

        public Criteria andRoleOfStakeholderInRegardsOfAqgrLike(String value) {
            addCriterion("role_of_stakeholder_in_regards_of_aqgr like", value, "roleOfStakeholderInRegardsOfAqgr");
            return (Criteria) this;
        }

        public Criteria andRoleOfStakeholderInRegardsOfAqgrNotLike(String value) {
            addCriterion("role_of_stakeholder_in_regards_of_aqgr not like", value, "roleOfStakeholderInRegardsOfAqgr");
            return (Criteria) this;
        }

        public Criteria andRoleOfStakeholderInRegardsOfAqgrIn(List<String> values) {
            addCriterion("role_of_stakeholder_in_regards_of_aqgr in", values, "roleOfStakeholderInRegardsOfAqgr");
            return (Criteria) this;
        }

        public Criteria andRoleOfStakeholderInRegardsOfAqgrNotIn(List<String> values) {
            addCriterion("role_of_stakeholder_in_regards_of_aqgr not in", values, "roleOfStakeholderInRegardsOfAqgr");
            return (Criteria) this;
        }

        public Criteria andRoleOfStakeholderInRegardsOfAqgrBetween(String value1, String value2) {
            addCriterion("role_of_stakeholder_in_regards_of_aqgr between", value1, value2, "roleOfStakeholderInRegardsOfAqgr");
            return (Criteria) this;
        }

        public Criteria andRoleOfStakeholderInRegardsOfAqgrNotBetween(String value1, String value2) {
            addCriterion("role_of_stakeholder_in_regards_of_aqgr not between", value1, value2, "roleOfStakeholderInRegardsOfAqgr");
            return (Criteria) this;
        }

        public Criteria andOtherRoleIsNull() {
            addCriterion("other_role is null");
            return (Criteria) this;
        }

        public Criteria andOtherRoleIsNotNull() {
            addCriterion("other_role is not null");
            return (Criteria) this;
        }

        public Criteria andOtherRoleEqualTo(String value) {
            addCriterion("other_role =", value, "otherRole");
            return (Criteria) this;
        }

        public Criteria andOtherRoleNotEqualTo(String value) {
            addCriterion("other_role <>", value, "otherRole");
            return (Criteria) this;
        }

        public Criteria andOtherRoleGreaterThan(String value) {
            addCriterion("other_role >", value, "otherRole");
            return (Criteria) this;
        }

        public Criteria andOtherRoleGreaterThanOrEqualTo(String value) {
            addCriterion("other_role >=", value, "otherRole");
            return (Criteria) this;
        }

        public Criteria andOtherRoleLessThan(String value) {
            addCriterion("other_role <", value, "otherRole");
            return (Criteria) this;
        }

        public Criteria andOtherRoleLessThanOrEqualTo(String value) {
            addCriterion("other_role <=", value, "otherRole");
            return (Criteria) this;
        }

        public Criteria andOtherRoleLike(String value) {
            addCriterion("other_role like", value, "otherRole");
            return (Criteria) this;
        }

        public Criteria andOtherRoleNotLike(String value) {
            addCriterion("other_role not like", value, "otherRole");
            return (Criteria) this;
        }

        public Criteria andOtherRoleIn(List<String> values) {
            addCriterion("other_role in", values, "otherRole");
            return (Criteria) this;
        }

        public Criteria andOtherRoleNotIn(List<String> values) {
            addCriterion("other_role not in", values, "otherRole");
            return (Criteria) this;
        }

        public Criteria andOtherRoleBetween(String value1, String value2) {
            addCriterion("other_role between", value1, value2, "otherRole");
            return (Criteria) this;
        }

        public Criteria andOtherRoleNotBetween(String value1, String value2) {
            addCriterion("other_role not between", value1, value2, "otherRole");
            return (Criteria) this;
        }

        public Criteria andGeneticResourceOfMainInterestIsNull() {
            addCriterion("genetic_resource_of_main_interest is null");
            return (Criteria) this;
        }

        public Criteria andGeneticResourceOfMainInterestIsNotNull() {
            addCriterion("genetic_resource_of_main_interest is not null");
            return (Criteria) this;
        }

        public Criteria andGeneticResourceOfMainInterestEqualTo(String value) {
            addCriterion("genetic_resource_of_main_interest =", value, "geneticResourceOfMainInterest");
            return (Criteria) this;
        }

        public Criteria andGeneticResourceOfMainInterestNotEqualTo(String value) {
            addCriterion("genetic_resource_of_main_interest <>", value, "geneticResourceOfMainInterest");
            return (Criteria) this;
        }

        public Criteria andGeneticResourceOfMainInterestGreaterThan(String value) {
            addCriterion("genetic_resource_of_main_interest >", value, "geneticResourceOfMainInterest");
            return (Criteria) this;
        }

        public Criteria andGeneticResourceOfMainInterestGreaterThanOrEqualTo(String value) {
            addCriterion("genetic_resource_of_main_interest >=", value, "geneticResourceOfMainInterest");
            return (Criteria) this;
        }

        public Criteria andGeneticResourceOfMainInterestLessThan(String value) {
            addCriterion("genetic_resource_of_main_interest <", value, "geneticResourceOfMainInterest");
            return (Criteria) this;
        }

        public Criteria andGeneticResourceOfMainInterestLessThanOrEqualTo(String value) {
            addCriterion("genetic_resource_of_main_interest <=", value, "geneticResourceOfMainInterest");
            return (Criteria) this;
        }

        public Criteria andGeneticResourceOfMainInterestLike(String value) {
            addCriterion("genetic_resource_of_main_interest like", value, "geneticResourceOfMainInterest");
            return (Criteria) this;
        }

        public Criteria andGeneticResourceOfMainInterestNotLike(String value) {
            addCriterion("genetic_resource_of_main_interest not like", value, "geneticResourceOfMainInterest");
            return (Criteria) this;
        }

        public Criteria andGeneticResourceOfMainInterestIn(List<String> values) {
            addCriterion("genetic_resource_of_main_interest in", values, "geneticResourceOfMainInterest");
            return (Criteria) this;
        }

        public Criteria andGeneticResourceOfMainInterestNotIn(List<String> values) {
            addCriterion("genetic_resource_of_main_interest not in", values, "geneticResourceOfMainInterest");
            return (Criteria) this;
        }

        public Criteria andGeneticResourceOfMainInterestBetween(String value1, String value2) {
            addCriterion("genetic_resource_of_main_interest between", value1, value2, "geneticResourceOfMainInterest");
            return (Criteria) this;
        }

        public Criteria andGeneticResourceOfMainInterestNotBetween(String value1, String value2) {
            addCriterion("genetic_resource_of_main_interest not between", value1, value2, "geneticResourceOfMainInterest");
            return (Criteria) this;
        }

        public Criteria andCommentsIsNull() {
            addCriterion("comments is null");
            return (Criteria) this;
        }

        public Criteria andCommentsIsNotNull() {
            addCriterion("comments is not null");
            return (Criteria) this;
        }

        public Criteria andCommentsEqualTo(String value) {
            addCriterion("comments =", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsNotEqualTo(String value) {
            addCriterion("comments <>", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsGreaterThan(String value) {
            addCriterion("comments >", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsGreaterThanOrEqualTo(String value) {
            addCriterion("comments >=", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsLessThan(String value) {
            addCriterion("comments <", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsLessThanOrEqualTo(String value) {
            addCriterion("comments <=", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsLike(String value) {
            addCriterion("comments like", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsNotLike(String value) {
            addCriterion("comments not like", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsIn(List<String> values) {
            addCriterion("comments in", values, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsNotIn(List<String> values) {
            addCriterion("comments not in", values, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsBetween(String value1, String value2) {
            addCriterion("comments between", value1, value2, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsNotBetween(String value1, String value2) {
            addCriterion("comments not between", value1, value2, "comments");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.Question31
     *
     * @mbg.generated do_not_delete_during_merge Tue Oct 10 14:03:47 CEST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.Question31
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}