package org.fao.fir.cgrfa.dao.mapper.model;

public class Question42MoreInformation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Question42_more_information.country
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Question42_more_information.region
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private String region;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Question42_more_information.geographic_region
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private String geographicRegion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Question42_more_information.economic_region
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private String economicRegion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Question42_more_information.other_capacity_building_needs_in_regards_to_aqgr
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private String otherCapacityBuildingNeedsInRegardsToAqgr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Question42_more_information.country
     *
     * @return the value of public.Question42_more_information.country
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Question42_more_information.country
     *
     * @param country the value for public.Question42_more_information.country
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Question42_more_information.region
     *
     * @return the value of public.Question42_more_information.region
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Question42_more_information.region
     *
     * @param region the value for public.Question42_more_information.region
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setRegion(String region) {
        this.region = region == null ? null : region.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Question42_more_information.geographic_region
     *
     * @return the value of public.Question42_more_information.geographic_region
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public String getGeographicRegion() {
        return geographicRegion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Question42_more_information.geographic_region
     *
     * @param geographicRegion the value for public.Question42_more_information.geographic_region
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setGeographicRegion(String geographicRegion) {
        this.geographicRegion = geographicRegion == null ? null : geographicRegion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Question42_more_information.economic_region
     *
     * @return the value of public.Question42_more_information.economic_region
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public String getEconomicRegion() {
        return economicRegion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Question42_more_information.economic_region
     *
     * @param economicRegion the value for public.Question42_more_information.economic_region
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setEconomicRegion(String economicRegion) {
        this.economicRegion = economicRegion == null ? null : economicRegion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Question42_more_information.other_capacity_building_needs_in_regards_to_aqgr
     *
     * @return the value of public.Question42_more_information.other_capacity_building_needs_in_regards_to_aqgr
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public String getOtherCapacityBuildingNeedsInRegardsToAqgr() {
        return otherCapacityBuildingNeedsInRegardsToAqgr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Question42_more_information.other_capacity_building_needs_in_regards_to_aqgr
     *
     * @param otherCapacityBuildingNeedsInRegardsToAqgr the value for public.Question42_more_information.other_capacity_building_needs_in_regards_to_aqgr
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setOtherCapacityBuildingNeedsInRegardsToAqgr(String otherCapacityBuildingNeedsInRegardsToAqgr) {
        this.otherCapacityBuildingNeedsInRegardsToAqgr = otherCapacityBuildingNeedsInRegardsToAqgr == null ? null : otherCapacityBuildingNeedsInRegardsToAqgr.trim();
    }
}