package org.fao.fir.cgrfa.dao.mapper.model;

public class Question38 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Question38.rownumber
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private Integer rownumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Question38.country
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Question38.region
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private String region;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Question38.geographic_region
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private String geographicRegion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Question38.economic_region
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private String economicRegion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Question38.main_institution_organization_corporation_and_other_entities
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private String mainInstitutionOrganizationCorporationAndOtherEntities;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Question38.type_of_genetic_resource
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private String typeOfGeneticResource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Question38.comments
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private String comments;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Question38.rownumber
     *
     * @return the value of public.Question38.rownumber
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public Integer getRownumber() {
        return rownumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Question38.rownumber
     *
     * @param rownumber the value for public.Question38.rownumber
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setRownumber(Integer rownumber) {
        this.rownumber = rownumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Question38.country
     *
     * @return the value of public.Question38.country
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Question38.country
     *
     * @param country the value for public.Question38.country
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Question38.region
     *
     * @return the value of public.Question38.region
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Question38.region
     *
     * @param region the value for public.Question38.region
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setRegion(String region) {
        this.region = region == null ? null : region.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Question38.geographic_region
     *
     * @return the value of public.Question38.geographic_region
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public String getGeographicRegion() {
        return geographicRegion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Question38.geographic_region
     *
     * @param geographicRegion the value for public.Question38.geographic_region
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setGeographicRegion(String geographicRegion) {
        this.geographicRegion = geographicRegion == null ? null : geographicRegion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Question38.economic_region
     *
     * @return the value of public.Question38.economic_region
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public String getEconomicRegion() {
        return economicRegion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Question38.economic_region
     *
     * @param economicRegion the value for public.Question38.economic_region
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setEconomicRegion(String economicRegion) {
        this.economicRegion = economicRegion == null ? null : economicRegion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Question38.main_institution_organization_corporation_and_other_entities
     *
     * @return the value of public.Question38.main_institution_organization_corporation_and_other_entities
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public String getMainInstitutionOrganizationCorporationAndOtherEntities() {
        return mainInstitutionOrganizationCorporationAndOtherEntities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Question38.main_institution_organization_corporation_and_other_entities
     *
     * @param mainInstitutionOrganizationCorporationAndOtherEntities the value for public.Question38.main_institution_organization_corporation_and_other_entities
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setMainInstitutionOrganizationCorporationAndOtherEntities(String mainInstitutionOrganizationCorporationAndOtherEntities) {
        this.mainInstitutionOrganizationCorporationAndOtherEntities = mainInstitutionOrganizationCorporationAndOtherEntities == null ? null : mainInstitutionOrganizationCorporationAndOtherEntities.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Question38.type_of_genetic_resource
     *
     * @return the value of public.Question38.type_of_genetic_resource
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public String getTypeOfGeneticResource() {
        return typeOfGeneticResource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Question38.type_of_genetic_resource
     *
     * @param typeOfGeneticResource the value for public.Question38.type_of_genetic_resource
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setTypeOfGeneticResource(String typeOfGeneticResource) {
        this.typeOfGeneticResource = typeOfGeneticResource == null ? null : typeOfGeneticResource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Question38.comments
     *
     * @return the value of public.Question38.comments
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Question38.comments
     *
     * @param comments the value for public.Question38.comments
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }
}