package org.fao.fir.cgrfa.dao.mapper.model;

public class Quest49 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Quest49.country
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Quest49.classtype
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    private String classtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Quest49.continent
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    private String continent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Quest49.region
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    private String region;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Quest49.surveyid
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    private Integer surveyid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Quest49.surveysort
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    private Integer surveysort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Quest49.surveyrow
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    private Integer surveyrow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Quest49.col1value
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    private String col1value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Quest49.col1radio
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    private String col1radio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Quest49.col2value
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    private String col2value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Quest49.country
     *
     * @return the value of public.Quest49.country
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Quest49.country
     *
     * @param country the value for public.Quest49.country
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Quest49.classtype
     *
     * @return the value of public.Quest49.classtype
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    public String getClasstype() {
        return classtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Quest49.classtype
     *
     * @param classtype the value for public.Quest49.classtype
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    public void setClasstype(String classtype) {
        this.classtype = classtype == null ? null : classtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Quest49.continent
     *
     * @return the value of public.Quest49.continent
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    public String getContinent() {
        return continent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Quest49.continent
     *
     * @param continent the value for public.Quest49.continent
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    public void setContinent(String continent) {
        this.continent = continent == null ? null : continent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Quest49.region
     *
     * @return the value of public.Quest49.region
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Quest49.region
     *
     * @param region the value for public.Quest49.region
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    public void setRegion(String region) {
        this.region = region == null ? null : region.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Quest49.surveyid
     *
     * @return the value of public.Quest49.surveyid
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    public Integer getSurveyid() {
        return surveyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Quest49.surveyid
     *
     * @param surveyid the value for public.Quest49.surveyid
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    public void setSurveyid(Integer surveyid) {
        this.surveyid = surveyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Quest49.surveysort
     *
     * @return the value of public.Quest49.surveysort
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    public Integer getSurveysort() {
        return surveysort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Quest49.surveysort
     *
     * @param surveysort the value for public.Quest49.surveysort
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    public void setSurveysort(Integer surveysort) {
        this.surveysort = surveysort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Quest49.surveyrow
     *
     * @return the value of public.Quest49.surveyrow
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    public Integer getSurveyrow() {
        return surveyrow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Quest49.surveyrow
     *
     * @param surveyrow the value for public.Quest49.surveyrow
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    public void setSurveyrow(Integer surveyrow) {
        this.surveyrow = surveyrow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Quest49.col1value
     *
     * @return the value of public.Quest49.col1value
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    public String getCol1value() {
        return col1value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Quest49.col1value
     *
     * @param col1value the value for public.Quest49.col1value
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    public void setCol1value(String col1value) {
        this.col1value = col1value == null ? null : col1value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Quest49.col1radio
     *
     * @return the value of public.Quest49.col1radio
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    public String getCol1radio() {
        return col1radio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Quest49.col1radio
     *
     * @param col1radio the value for public.Quest49.col1radio
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    public void setCol1radio(String col1radio) {
        this.col1radio = col1radio == null ? null : col1radio.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Quest49.col2value
     *
     * @return the value of public.Quest49.col2value
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    public String getCol2value() {
        return col2value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Quest49.col2value
     *
     * @param col2value the value for public.Quest49.col2value
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    public void setCol2value(String col2value) {
        this.col2value = col2value == null ? null : col2value.trim();
    }
}