package org.fao.fir.cgrfa.dao.mapper.model;

public class Quest10 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Quest10.country
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Quest10.classtype
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    private String classtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Quest10.continent
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    private String continent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Quest10.region
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    private String region;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Quest10.surveyid
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    private Integer surveyid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Quest10.surveysort
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    private Integer surveysort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Quest10.col1species
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    private String col1species;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Quest10.col2value
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    private String col2value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Quest10.col2radio
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    private String col2radio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Quest10.col3value
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    private String col3value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Quest10.country
     *
     * @return the value of public.Quest10.country
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Quest10.country
     *
     * @param country the value for public.Quest10.country
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Quest10.classtype
     *
     * @return the value of public.Quest10.classtype
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    public String getClasstype() {
        return classtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Quest10.classtype
     *
     * @param classtype the value for public.Quest10.classtype
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    public void setClasstype(String classtype) {
        this.classtype = classtype == null ? null : classtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Quest10.continent
     *
     * @return the value of public.Quest10.continent
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    public String getContinent() {
        return continent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Quest10.continent
     *
     * @param continent the value for public.Quest10.continent
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    public void setContinent(String continent) {
        this.continent = continent == null ? null : continent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Quest10.region
     *
     * @return the value of public.Quest10.region
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Quest10.region
     *
     * @param region the value for public.Quest10.region
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    public void setRegion(String region) {
        this.region = region == null ? null : region.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Quest10.surveyid
     *
     * @return the value of public.Quest10.surveyid
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    public Integer getSurveyid() {
        return surveyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Quest10.surveyid
     *
     * @param surveyid the value for public.Quest10.surveyid
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    public void setSurveyid(Integer surveyid) {
        this.surveyid = surveyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Quest10.surveysort
     *
     * @return the value of public.Quest10.surveysort
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    public Integer getSurveysort() {
        return surveysort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Quest10.surveysort
     *
     * @param surveysort the value for public.Quest10.surveysort
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    public void setSurveysort(Integer surveysort) {
        this.surveysort = surveysort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Quest10.col1species
     *
     * @return the value of public.Quest10.col1species
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    public String getCol1species() {
        return col1species;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Quest10.col1species
     *
     * @param col1species the value for public.Quest10.col1species
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    public void setCol1species(String col1species) {
        this.col1species = col1species == null ? null : col1species.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Quest10.col2value
     *
     * @return the value of public.Quest10.col2value
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    public String getCol2value() {
        return col2value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Quest10.col2value
     *
     * @param col2value the value for public.Quest10.col2value
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    public void setCol2value(String col2value) {
        this.col2value = col2value == null ? null : col2value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Quest10.col2radio
     *
     * @return the value of public.Quest10.col2radio
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    public String getCol2radio() {
        return col2radio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Quest10.col2radio
     *
     * @param col2radio the value for public.Quest10.col2radio
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    public void setCol2radio(String col2radio) {
        this.col2radio = col2radio == null ? null : col2radio.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Quest10.col3value
     *
     * @return the value of public.Quest10.col3value
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    public String getCol3value() {
        return col3value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Quest10.col3value
     *
     * @param col3value the value for public.Quest10.col3value
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    public void setCol3value(String col3value) {
        this.col3value = col3value == null ? null : col3value.trim();
    }
}