package org.fao.fir.cgrfa.dao.mapper.model;

public class Question32 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Question32.rownumber
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private Integer rownumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Question32.country
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Question32.region
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private String region;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Question32.geographic_region
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private String geographicRegion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Question32.economic_region
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private String economicRegion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Question32.national_legislation_policy_and_or_mechanism
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private String nationalLegislationPolicyAndOrMechanism;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Question32.date_established
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private String dateEstablished;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Question32.scope
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private String scope;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Question32.comments
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private String comments;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Question32.rownumber
     *
     * @return the value of public.Question32.rownumber
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public Integer getRownumber() {
        return rownumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Question32.rownumber
     *
     * @param rownumber the value for public.Question32.rownumber
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setRownumber(Integer rownumber) {
        this.rownumber = rownumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Question32.country
     *
     * @return the value of public.Question32.country
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Question32.country
     *
     * @param country the value for public.Question32.country
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Question32.region
     *
     * @return the value of public.Question32.region
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Question32.region
     *
     * @param region the value for public.Question32.region
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setRegion(String region) {
        this.region = region == null ? null : region.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Question32.geographic_region
     *
     * @return the value of public.Question32.geographic_region
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public String getGeographicRegion() {
        return geographicRegion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Question32.geographic_region
     *
     * @param geographicRegion the value for public.Question32.geographic_region
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setGeographicRegion(String geographicRegion) {
        this.geographicRegion = geographicRegion == null ? null : geographicRegion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Question32.economic_region
     *
     * @return the value of public.Question32.economic_region
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public String getEconomicRegion() {
        return economicRegion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Question32.economic_region
     *
     * @param economicRegion the value for public.Question32.economic_region
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setEconomicRegion(String economicRegion) {
        this.economicRegion = economicRegion == null ? null : economicRegion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Question32.national_legislation_policy_and_or_mechanism
     *
     * @return the value of public.Question32.national_legislation_policy_and_or_mechanism
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public String getNationalLegislationPolicyAndOrMechanism() {
        return nationalLegislationPolicyAndOrMechanism;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Question32.national_legislation_policy_and_or_mechanism
     *
     * @param nationalLegislationPolicyAndOrMechanism the value for public.Question32.national_legislation_policy_and_or_mechanism
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setNationalLegislationPolicyAndOrMechanism(String nationalLegislationPolicyAndOrMechanism) {
        this.nationalLegislationPolicyAndOrMechanism = nationalLegislationPolicyAndOrMechanism == null ? null : nationalLegislationPolicyAndOrMechanism.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Question32.date_established
     *
     * @return the value of public.Question32.date_established
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public String getDateEstablished() {
        return dateEstablished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Question32.date_established
     *
     * @param dateEstablished the value for public.Question32.date_established
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setDateEstablished(String dateEstablished) {
        this.dateEstablished = dateEstablished == null ? null : dateEstablished.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Question32.scope
     *
     * @return the value of public.Question32.scope
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public String getScope() {
        return scope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Question32.scope
     *
     * @param scope the value for public.Question32.scope
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setScope(String scope) {
        this.scope = scope == null ? null : scope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Question32.comments
     *
     * @return the value of public.Question32.comments
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Question32.comments
     *
     * @param comments the value for public.Question32.comments
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }
}