package org.fao.fir.cgrfa.dao.mapper.model;

public class Questionstablesrows {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.QuestionsTablesRows.ID
     *
     * @mbggenerated Tue Jun 09 17:34:37 CEST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.QuestionsTablesRows.multi
     *
     * @mbggenerated Tue Jun 09 17:34:37 CEST 2015
     */
    private Short multi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.QuestionsTablesRows.table_ID
     *
     * @mbggenerated Tue Jun 09 17:34:37 CEST 2015
     */
    private Integer tableId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.QuestionsTablesRows.order
     *
     * @mbggenerated Tue Jun 09 17:34:37 CEST 2015
     */
    private Integer order;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.QuestionsTablesRows.name
     *
     * @mbggenerated Tue Jun 09 17:34:37 CEST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.QuestionsTablesRows.deleted
     *
     * @mbggenerated Tue Jun 09 17:34:37 CEST 2015
     */
    private Integer deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.QuestionsTablesRows.ID
     *
     * @return the value of public.QuestionsTablesRows.ID
     *
     * @mbggenerated Tue Jun 09 17:34:37 CEST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.QuestionsTablesRows.ID
     *
     * @param id the value for public.QuestionsTablesRows.ID
     *
     * @mbggenerated Tue Jun 09 17:34:37 CEST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.QuestionsTablesRows.multi
     *
     * @return the value of public.QuestionsTablesRows.multi
     *
     * @mbggenerated Tue Jun 09 17:34:37 CEST 2015
     */
    public Short getMulti() {
        return multi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.QuestionsTablesRows.multi
     *
     * @param multi the value for public.QuestionsTablesRows.multi
     *
     * @mbggenerated Tue Jun 09 17:34:37 CEST 2015
     */
    public void setMulti(Short multi) {
        this.multi = multi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.QuestionsTablesRows.table_ID
     *
     * @return the value of public.QuestionsTablesRows.table_ID
     *
     * @mbggenerated Tue Jun 09 17:34:37 CEST 2015
     */
    public Integer getTableId() {
        return tableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.QuestionsTablesRows.table_ID
     *
     * @param tableId the value for public.QuestionsTablesRows.table_ID
     *
     * @mbggenerated Tue Jun 09 17:34:37 CEST 2015
     */
    public void setTableId(Integer tableId) {
        this.tableId = tableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.QuestionsTablesRows.order
     *
     * @return the value of public.QuestionsTablesRows.order
     *
     * @mbggenerated Tue Jun 09 17:34:37 CEST 2015
     */
    public Integer getOrder() {
        return order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.QuestionsTablesRows.order
     *
     * @param order the value for public.QuestionsTablesRows.order
     *
     * @mbggenerated Tue Jun 09 17:34:37 CEST 2015
     */
    public void setOrder(Integer order) {
        this.order = order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.QuestionsTablesRows.name
     *
     * @return the value of public.QuestionsTablesRows.name
     *
     * @mbggenerated Tue Jun 09 17:34:37 CEST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.QuestionsTablesRows.name
     *
     * @param name the value for public.QuestionsTablesRows.name
     *
     * @mbggenerated Tue Jun 09 17:34:37 CEST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.QuestionsTablesRows.deleted
     *
     * @return the value of public.QuestionsTablesRows.deleted
     *
     * @mbggenerated Tue Jun 09 17:34:37 CEST 2015
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.QuestionsTablesRows.deleted
     *
     * @param deleted the value for public.QuestionsTablesRows.deleted
     *
     * @mbggenerated Tue Jun 09 17:34:37 CEST 2015
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }
}