package org.fao.fir.cgrfa.dao.mapper.model;

public class Questionstablesfields {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.QuestionsTablesFields.ID
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.QuestionsTablesFields.table_id
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private Integer tableId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.QuestionsTablesFields.column_id
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private Integer columnId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.QuestionsTablesFields.row_id
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private Integer rowId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.QuestionsTablesFields.type
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.QuestionsTablesFields.text_e
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private String textE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.QuestionsTablesFields.text_f
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private String textF;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.QuestionsTablesFields.text_s
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private String textS;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.QuestionsTablesFields.text_c
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private String textC;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.QuestionsTablesFields.text_r
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private String textR;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.QuestionsTablesFields.text_a
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private String textA;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.QuestionsTablesFields.name
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.QuestionsTablesFields.controlled_list
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private Integer controlledList;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.QuestionsTablesFields.default_value
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private String defaultValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.QuestionsTablesFields.deleted
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private Integer deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.QuestionsTablesFields.ID
     *
     * @return the value of public.QuestionsTablesFields.ID
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.QuestionsTablesFields.ID
     *
     * @param id the value for public.QuestionsTablesFields.ID
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.QuestionsTablesFields.table_id
     *
     * @return the value of public.QuestionsTablesFields.table_id
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public Integer getTableId() {
        return tableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.QuestionsTablesFields.table_id
     *
     * @param tableId the value for public.QuestionsTablesFields.table_id
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setTableId(Integer tableId) {
        this.tableId = tableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.QuestionsTablesFields.column_id
     *
     * @return the value of public.QuestionsTablesFields.column_id
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public Integer getColumnId() {
        return columnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.QuestionsTablesFields.column_id
     *
     * @param columnId the value for public.QuestionsTablesFields.column_id
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setColumnId(Integer columnId) {
        this.columnId = columnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.QuestionsTablesFields.row_id
     *
     * @return the value of public.QuestionsTablesFields.row_id
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public Integer getRowId() {
        return rowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.QuestionsTablesFields.row_id
     *
     * @param rowId the value for public.QuestionsTablesFields.row_id
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setRowId(Integer rowId) {
        this.rowId = rowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.QuestionsTablesFields.type
     *
     * @return the value of public.QuestionsTablesFields.type
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.QuestionsTablesFields.type
     *
     * @param type the value for public.QuestionsTablesFields.type
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.QuestionsTablesFields.text_e
     *
     * @return the value of public.QuestionsTablesFields.text_e
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public String getTextE() {
        return textE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.QuestionsTablesFields.text_e
     *
     * @param textE the value for public.QuestionsTablesFields.text_e
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setTextE(String textE) {
        this.textE = textE == null ? null : textE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.QuestionsTablesFields.text_f
     *
     * @return the value of public.QuestionsTablesFields.text_f
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public String getTextF() {
        return textF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.QuestionsTablesFields.text_f
     *
     * @param textF the value for public.QuestionsTablesFields.text_f
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setTextF(String textF) {
        this.textF = textF == null ? null : textF.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.QuestionsTablesFields.text_s
     *
     * @return the value of public.QuestionsTablesFields.text_s
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public String getTextS() {
        return textS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.QuestionsTablesFields.text_s
     *
     * @param textS the value for public.QuestionsTablesFields.text_s
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setTextS(String textS) {
        this.textS = textS == null ? null : textS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.QuestionsTablesFields.text_c
     *
     * @return the value of public.QuestionsTablesFields.text_c
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public String getTextC() {
        return textC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.QuestionsTablesFields.text_c
     *
     * @param textC the value for public.QuestionsTablesFields.text_c
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setTextC(String textC) {
        this.textC = textC == null ? null : textC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.QuestionsTablesFields.text_r
     *
     * @return the value of public.QuestionsTablesFields.text_r
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public String getTextR() {
        return textR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.QuestionsTablesFields.text_r
     *
     * @param textR the value for public.QuestionsTablesFields.text_r
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setTextR(String textR) {
        this.textR = textR == null ? null : textR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.QuestionsTablesFields.text_a
     *
     * @return the value of public.QuestionsTablesFields.text_a
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public String getTextA() {
        return textA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.QuestionsTablesFields.text_a
     *
     * @param textA the value for public.QuestionsTablesFields.text_a
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setTextA(String textA) {
        this.textA = textA == null ? null : textA.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.QuestionsTablesFields.name
     *
     * @return the value of public.QuestionsTablesFields.name
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.QuestionsTablesFields.name
     *
     * @param name the value for public.QuestionsTablesFields.name
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.QuestionsTablesFields.controlled_list
     *
     * @return the value of public.QuestionsTablesFields.controlled_list
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public Integer getControlledList() {
        return controlledList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.QuestionsTablesFields.controlled_list
     *
     * @param controlledList the value for public.QuestionsTablesFields.controlled_list
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setControlledList(Integer controlledList) {
        this.controlledList = controlledList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.QuestionsTablesFields.default_value
     *
     * @return the value of public.QuestionsTablesFields.default_value
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public String getDefaultValue() {
        return defaultValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.QuestionsTablesFields.default_value
     *
     * @param defaultValue the value for public.QuestionsTablesFields.default_value
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setDefaultValue(String defaultValue) {
        this.defaultValue = defaultValue == null ? null : defaultValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.QuestionsTablesFields.deleted
     *
     * @return the value of public.QuestionsTablesFields.deleted
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.QuestionsTablesFields.deleted
     *
     * @param deleted the value for public.QuestionsTablesFields.deleted
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }
}