package org.fao.fir.cgrfa.dao.mapper.model;

public class Question00Introduction {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Question00_Introduction.country
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Question00_Introduction.region
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private String region;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Question00_Introduction.geographic_region
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private String geographicRegion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Question00_Introduction.economic_region
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private String economicRegion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Question00_Introduction.introduction
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private String introduction;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Question00_Introduction.country
     *
     * @return the value of public.Question00_Introduction.country
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Question00_Introduction.country
     *
     * @param country the value for public.Question00_Introduction.country
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Question00_Introduction.region
     *
     * @return the value of public.Question00_Introduction.region
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Question00_Introduction.region
     *
     * @param region the value for public.Question00_Introduction.region
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setRegion(String region) {
        this.region = region == null ? null : region.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Question00_Introduction.geographic_region
     *
     * @return the value of public.Question00_Introduction.geographic_region
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public String getGeographicRegion() {
        return geographicRegion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Question00_Introduction.geographic_region
     *
     * @param geographicRegion the value for public.Question00_Introduction.geographic_region
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setGeographicRegion(String geographicRegion) {
        this.geographicRegion = geographicRegion == null ? null : geographicRegion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Question00_Introduction.economic_region
     *
     * @return the value of public.Question00_Introduction.economic_region
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public String getEconomicRegion() {
        return economicRegion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Question00_Introduction.economic_region
     *
     * @param economicRegion the value for public.Question00_Introduction.economic_region
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setEconomicRegion(String economicRegion) {
        this.economicRegion = economicRegion == null ? null : economicRegion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Question00_Introduction.introduction
     *
     * @return the value of public.Question00_Introduction.introduction
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Question00_Introduction.introduction
     *
     * @param introduction the value for public.Question00_Introduction.introduction
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }
}