package org.fao.fir.cgrfa.dao.mapper.model;

import java.util.ArrayList;
import java.util.List;

public class SurveydataExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.SurveyData
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.SurveyData
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.SurveyData
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.SurveyData
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public SurveydataExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.SurveyData
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.SurveyData
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.SurveyData
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.SurveyData
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.SurveyData
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.SurveyData
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.SurveyData
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.SurveyData
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.SurveyData
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.SurveyData
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.SurveyData
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSurveyIdIsNull() {
            addCriterion("survey_id is null");
            return (Criteria) this;
        }

        public Criteria andSurveyIdIsNotNull() {
            addCriterion("survey_id is not null");
            return (Criteria) this;
        }

        public Criteria andSurveyIdEqualTo(Integer value) {
            addCriterion("survey_id =", value, "surveyId");
            return (Criteria) this;
        }

        public Criteria andSurveyIdNotEqualTo(Integer value) {
            addCriterion("survey_id <>", value, "surveyId");
            return (Criteria) this;
        }

        public Criteria andSurveyIdGreaterThan(Integer value) {
            addCriterion("survey_id >", value, "surveyId");
            return (Criteria) this;
        }

        public Criteria andSurveyIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("survey_id >=", value, "surveyId");
            return (Criteria) this;
        }

        public Criteria andSurveyIdLessThan(Integer value) {
            addCriterion("survey_id <", value, "surveyId");
            return (Criteria) this;
        }

        public Criteria andSurveyIdLessThanOrEqualTo(Integer value) {
            addCriterion("survey_id <=", value, "surveyId");
            return (Criteria) this;
        }

        public Criteria andSurveyIdIn(List<Integer> values) {
            addCriterion("survey_id in", values, "surveyId");
            return (Criteria) this;
        }

        public Criteria andSurveyIdNotIn(List<Integer> values) {
            addCriterion("survey_id not in", values, "surveyId");
            return (Criteria) this;
        }

        public Criteria andSurveyIdBetween(Integer value1, Integer value2) {
            addCriterion("survey_id between", value1, value2, "surveyId");
            return (Criteria) this;
        }

        public Criteria andSurveyIdNotBetween(Integer value1, Integer value2) {
            addCriterion("survey_id not between", value1, value2, "surveyId");
            return (Criteria) this;
        }

        public Criteria andFieldIsNull() {
            addCriterion("field is null");
            return (Criteria) this;
        }

        public Criteria andFieldIsNotNull() {
            addCriterion("field is not null");
            return (Criteria) this;
        }

        public Criteria andFieldEqualTo(String value) {
            addCriterion("field =", value, "field");
            return (Criteria) this;
        }

        public Criteria andFieldNotEqualTo(String value) {
            addCriterion("field <>", value, "field");
            return (Criteria) this;
        }

        public Criteria andFieldGreaterThan(String value) {
            addCriterion("field >", value, "field");
            return (Criteria) this;
        }

        public Criteria andFieldGreaterThanOrEqualTo(String value) {
            addCriterion("field >=", value, "field");
            return (Criteria) this;
        }

        public Criteria andFieldLessThan(String value) {
            addCriterion("field <", value, "field");
            return (Criteria) this;
        }

        public Criteria andFieldLessThanOrEqualTo(String value) {
            addCriterion("field <=", value, "field");
            return (Criteria) this;
        }

        public Criteria andFieldLike(String value) {
            addCriterion("field like", value, "field");
            return (Criteria) this;
        }

        public Criteria andFieldNotLike(String value) {
            addCriterion("field not like", value, "field");
            return (Criteria) this;
        }

        public Criteria andFieldIn(List<String> values) {
            addCriterion("field in", values, "field");
            return (Criteria) this;
        }

        public Criteria andFieldNotIn(List<String> values) {
            addCriterion("field not in", values, "field");
            return (Criteria) this;
        }

        public Criteria andFieldBetween(String value1, String value2) {
            addCriterion("field between", value1, value2, "field");
            return (Criteria) this;
        }

        public Criteria andFieldNotBetween(String value1, String value2) {
            addCriterion("field not between", value1, value2, "field");
            return (Criteria) this;
        }

        public Criteria andTableRowMultiSortIsNull() {
            addCriterion("table_row_multi_sort is null");
            return (Criteria) this;
        }

        public Criteria andTableRowMultiSortIsNotNull() {
            addCriterion("table_row_multi_sort is not null");
            return (Criteria) this;
        }

        public Criteria andTableRowMultiSortEqualTo(Integer value) {
            addCriterion("table_row_multi_sort =", value, "tableRowMultiSort");
            return (Criteria) this;
        }

        public Criteria andTableRowMultiSortNotEqualTo(Integer value) {
            addCriterion("table_row_multi_sort <>", value, "tableRowMultiSort");
            return (Criteria) this;
        }

        public Criteria andTableRowMultiSortGreaterThan(Integer value) {
            addCriterion("table_row_multi_sort >", value, "tableRowMultiSort");
            return (Criteria) this;
        }

        public Criteria andTableRowMultiSortGreaterThanOrEqualTo(Integer value) {
            addCriterion("table_row_multi_sort >=", value, "tableRowMultiSort");
            return (Criteria) this;
        }

        public Criteria andTableRowMultiSortLessThan(Integer value) {
            addCriterion("table_row_multi_sort <", value, "tableRowMultiSort");
            return (Criteria) this;
        }

        public Criteria andTableRowMultiSortLessThanOrEqualTo(Integer value) {
            addCriterion("table_row_multi_sort <=", value, "tableRowMultiSort");
            return (Criteria) this;
        }

        public Criteria andTableRowMultiSortIn(List<Integer> values) {
            addCriterion("table_row_multi_sort in", values, "tableRowMultiSort");
            return (Criteria) this;
        }

        public Criteria andTableRowMultiSortNotIn(List<Integer> values) {
            addCriterion("table_row_multi_sort not in", values, "tableRowMultiSort");
            return (Criteria) this;
        }

        public Criteria andTableRowMultiSortBetween(Integer value1, Integer value2) {
            addCriterion("table_row_multi_sort between", value1, value2, "tableRowMultiSort");
            return (Criteria) this;
        }

        public Criteria andTableRowMultiSortNotBetween(Integer value1, Integer value2) {
            addCriterion("table_row_multi_sort not between", value1, value2, "tableRowMultiSort");
            return (Criteria) this;
        }

        public Criteria andTableRowIdIsNull() {
            addCriterion("table_row_id is null");
            return (Criteria) this;
        }

        public Criteria andTableRowIdIsNotNull() {
            addCriterion("table_row_id is not null");
            return (Criteria) this;
        }

        public Criteria andTableRowIdEqualTo(Integer value) {
            addCriterion("table_row_id =", value, "tableRowId");
            return (Criteria) this;
        }

        public Criteria andTableRowIdNotEqualTo(Integer value) {
            addCriterion("table_row_id <>", value, "tableRowId");
            return (Criteria) this;
        }

        public Criteria andTableRowIdGreaterThan(Integer value) {
            addCriterion("table_row_id >", value, "tableRowId");
            return (Criteria) this;
        }

        public Criteria andTableRowIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("table_row_id >=", value, "tableRowId");
            return (Criteria) this;
        }

        public Criteria andTableRowIdLessThan(Integer value) {
            addCriterion("table_row_id <", value, "tableRowId");
            return (Criteria) this;
        }

        public Criteria andTableRowIdLessThanOrEqualTo(Integer value) {
            addCriterion("table_row_id <=", value, "tableRowId");
            return (Criteria) this;
        }

        public Criteria andTableRowIdIn(List<Integer> values) {
            addCriterion("table_row_id in", values, "tableRowId");
            return (Criteria) this;
        }

        public Criteria andTableRowIdNotIn(List<Integer> values) {
            addCriterion("table_row_id not in", values, "tableRowId");
            return (Criteria) this;
        }

        public Criteria andTableRowIdBetween(Integer value1, Integer value2) {
            addCriterion("table_row_id between", value1, value2, "tableRowId");
            return (Criteria) this;
        }

        public Criteria andTableRowIdNotBetween(Integer value1, Integer value2) {
            addCriterion("table_row_id not between", value1, value2, "tableRowId");
            return (Criteria) this;
        }

        public Criteria andOldkeyIsNull() {
            addCriterion("oldkey is null");
            return (Criteria) this;
        }

        public Criteria andOldkeyIsNotNull() {
            addCriterion("oldkey is not null");
            return (Criteria) this;
        }

        public Criteria andOldkeyEqualTo(Integer value) {
            addCriterion("oldkey =", value, "oldkey");
            return (Criteria) this;
        }

        public Criteria andOldkeyNotEqualTo(Integer value) {
            addCriterion("oldkey <>", value, "oldkey");
            return (Criteria) this;
        }

        public Criteria andOldkeyGreaterThan(Integer value) {
            addCriterion("oldkey >", value, "oldkey");
            return (Criteria) this;
        }

        public Criteria andOldkeyGreaterThanOrEqualTo(Integer value) {
            addCriterion("oldkey >=", value, "oldkey");
            return (Criteria) this;
        }

        public Criteria andOldkeyLessThan(Integer value) {
            addCriterion("oldkey <", value, "oldkey");
            return (Criteria) this;
        }

        public Criteria andOldkeyLessThanOrEqualTo(Integer value) {
            addCriterion("oldkey <=", value, "oldkey");
            return (Criteria) this;
        }

        public Criteria andOldkeyIn(List<Integer> values) {
            addCriterion("oldkey in", values, "oldkey");
            return (Criteria) this;
        }

        public Criteria andOldkeyNotIn(List<Integer> values) {
            addCriterion("oldkey not in", values, "oldkey");
            return (Criteria) this;
        }

        public Criteria andOldkeyBetween(Integer value1, Integer value2) {
            addCriterion("oldkey between", value1, value2, "oldkey");
            return (Criteria) this;
        }

        public Criteria andOldkeyNotBetween(Integer value1, Integer value2) {
            addCriterion("oldkey not between", value1, value2, "oldkey");
            return (Criteria) this;
        }

        public Criteria andValueIsNull() {
            addCriterion("value is null");
            return (Criteria) this;
        }

        public Criteria andValueIsNotNull() {
            addCriterion("value is not null");
            return (Criteria) this;
        }

        public Criteria andValueEqualTo(String value) {
            addCriterion("value =", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueNotEqualTo(String value) {
            addCriterion("value <>", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueGreaterThan(String value) {
            addCriterion("value >", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueGreaterThanOrEqualTo(String value) {
            addCriterion("value >=", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueLessThan(String value) {
            addCriterion("value <", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueLessThanOrEqualTo(String value) {
            addCriterion("value <=", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueLike(String value) {
            addCriterion("value like", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueNotLike(String value) {
            addCriterion("value not like", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueIn(List<String> values) {
            addCriterion("value in", values, "value");
            return (Criteria) this;
        }

        public Criteria andValueNotIn(List<String> values) {
            addCriterion("value not in", values, "value");
            return (Criteria) this;
        }

        public Criteria andValueBetween(String value1, String value2) {
            addCriterion("value between", value1, value2, "value");
            return (Criteria) this;
        }

        public Criteria andValueNotBetween(String value1, String value2) {
            addCriterion("value not between", value1, value2, "value");
            return (Criteria) this;
        }

        public Criteria andValueOptIsNull() {
            addCriterion("value_opt is null");
            return (Criteria) this;
        }

        public Criteria andValueOptIsNotNull() {
            addCriterion("value_opt is not null");
            return (Criteria) this;
        }

        public Criteria andValueOptEqualTo(String value) {
            addCriterion("value_opt =", value, "valueOpt");
            return (Criteria) this;
        }

        public Criteria andValueOptNotEqualTo(String value) {
            addCriterion("value_opt <>", value, "valueOpt");
            return (Criteria) this;
        }

        public Criteria andValueOptGreaterThan(String value) {
            addCriterion("value_opt >", value, "valueOpt");
            return (Criteria) this;
        }

        public Criteria andValueOptGreaterThanOrEqualTo(String value) {
            addCriterion("value_opt >=", value, "valueOpt");
            return (Criteria) this;
        }

        public Criteria andValueOptLessThan(String value) {
            addCriterion("value_opt <", value, "valueOpt");
            return (Criteria) this;
        }

        public Criteria andValueOptLessThanOrEqualTo(String value) {
            addCriterion("value_opt <=", value, "valueOpt");
            return (Criteria) this;
        }

        public Criteria andValueOptLike(String value) {
            addCriterion("value_opt like", value, "valueOpt");
            return (Criteria) this;
        }

        public Criteria andValueOptNotLike(String value) {
            addCriterion("value_opt not like", value, "valueOpt");
            return (Criteria) this;
        }

        public Criteria andValueOptIn(List<String> values) {
            addCriterion("value_opt in", values, "valueOpt");
            return (Criteria) this;
        }

        public Criteria andValueOptNotIn(List<String> values) {
            addCriterion("value_opt not in", values, "valueOpt");
            return (Criteria) this;
        }

        public Criteria andValueOptBetween(String value1, String value2) {
            addCriterion("value_opt between", value1, value2, "valueOpt");
            return (Criteria) this;
        }

        public Criteria andValueOptNotBetween(String value1, String value2) {
            addCriterion("value_opt not between", value1, value2, "valueOpt");
            return (Criteria) this;
        }

        public Criteria andOriginalIsNull() {
            addCriterion("original is null");
            return (Criteria) this;
        }

        public Criteria andOriginalIsNotNull() {
            addCriterion("original is not null");
            return (Criteria) this;
        }

        public Criteria andOriginalEqualTo(String value) {
            addCriterion("original =", value, "original");
            return (Criteria) this;
        }

        public Criteria andOriginalNotEqualTo(String value) {
            addCriterion("original <>", value, "original");
            return (Criteria) this;
        }

        public Criteria andOriginalGreaterThan(String value) {
            addCriterion("original >", value, "original");
            return (Criteria) this;
        }

        public Criteria andOriginalGreaterThanOrEqualTo(String value) {
            addCriterion("original >=", value, "original");
            return (Criteria) this;
        }

        public Criteria andOriginalLessThan(String value) {
            addCriterion("original <", value, "original");
            return (Criteria) this;
        }

        public Criteria andOriginalLessThanOrEqualTo(String value) {
            addCriterion("original <=", value, "original");
            return (Criteria) this;
        }

        public Criteria andOriginalLike(String value) {
            addCriterion("original like", value, "original");
            return (Criteria) this;
        }

        public Criteria andOriginalNotLike(String value) {
            addCriterion("original not like", value, "original");
            return (Criteria) this;
        }

        public Criteria andOriginalIn(List<String> values) {
            addCriterion("original in", values, "original");
            return (Criteria) this;
        }

        public Criteria andOriginalNotIn(List<String> values) {
            addCriterion("original not in", values, "original");
            return (Criteria) this;
        }

        public Criteria andOriginalBetween(String value1, String value2) {
            addCriterion("original between", value1, value2, "original");
            return (Criteria) this;
        }

        public Criteria andOriginalNotBetween(String value1, String value2) {
            addCriterion("original not between", value1, value2, "original");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.SurveyData
     *
     * @mbg.generated do_not_delete_during_merge Tue Oct 10 14:03:47 CEST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.SurveyData
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}