package org.fao.fir.cgrfa.dao.mapper.model;

import java.util.Date;

public class Surveynotdeleted {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.SurveyNotDeleted.ID
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.SurveyNotDeleted.date
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.SurveyNotDeleted.country
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private Integer country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.SurveyNotDeleted.name
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.SurveyNotDeleted.prepared_by
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private String preparedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.SurveyNotDeleted.deleted
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private Integer deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.SurveyNotDeleted.inserted_date
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private Date insertedDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.SurveyNotDeleted.modified_date
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    private Date modifiedDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.SurveyNotDeleted.ID
     *
     * @return the value of public.SurveyNotDeleted.ID
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.SurveyNotDeleted.ID
     *
     * @param id the value for public.SurveyNotDeleted.ID
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.SurveyNotDeleted.date
     *
     * @return the value of public.SurveyNotDeleted.date
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.SurveyNotDeleted.date
     *
     * @param date the value for public.SurveyNotDeleted.date
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.SurveyNotDeleted.country
     *
     * @return the value of public.SurveyNotDeleted.country
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public Integer getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.SurveyNotDeleted.country
     *
     * @param country the value for public.SurveyNotDeleted.country
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setCountry(Integer country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.SurveyNotDeleted.name
     *
     * @return the value of public.SurveyNotDeleted.name
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.SurveyNotDeleted.name
     *
     * @param name the value for public.SurveyNotDeleted.name
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.SurveyNotDeleted.prepared_by
     *
     * @return the value of public.SurveyNotDeleted.prepared_by
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public String getPreparedBy() {
        return preparedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.SurveyNotDeleted.prepared_by
     *
     * @param preparedBy the value for public.SurveyNotDeleted.prepared_by
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setPreparedBy(String preparedBy) {
        this.preparedBy = preparedBy == null ? null : preparedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.SurveyNotDeleted.deleted
     *
     * @return the value of public.SurveyNotDeleted.deleted
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.SurveyNotDeleted.deleted
     *
     * @param deleted the value for public.SurveyNotDeleted.deleted
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.SurveyNotDeleted.inserted_date
     *
     * @return the value of public.SurveyNotDeleted.inserted_date
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public Date getInsertedDate() {
        return insertedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.SurveyNotDeleted.inserted_date
     *
     * @param insertedDate the value for public.SurveyNotDeleted.inserted_date
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setInsertedDate(Date insertedDate) {
        this.insertedDate = insertedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.SurveyNotDeleted.modified_date
     *
     * @return the value of public.SurveyNotDeleted.modified_date
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public Date getModifiedDate() {
        return modifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.SurveyNotDeleted.modified_date
     *
     * @param modifiedDate the value for public.SurveyNotDeleted.modified_date
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
}