package org.fao.fir.cgrfa.dao.mapper.model;

public class SurveystatusIdSeq {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.SurveyStatus_ID_seq.sequence_name
     *
     * @mbggenerated Mon May 11 14:33:35 CEST 2015
     */
    private String sequenceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.SurveyStatus_ID_seq.last_value
     *
     * @mbggenerated Mon May 11 14:33:35 CEST 2015
     */
    private Long lastValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.SurveyStatus_ID_seq.start_value
     *
     * @mbggenerated Mon May 11 14:33:35 CEST 2015
     */
    private Long startValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.SurveyStatus_ID_seq.increment_by
     *
     * @mbggenerated Mon May 11 14:33:35 CEST 2015
     */
    private Long incrementBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.SurveyStatus_ID_seq.max_value
     *
     * @mbggenerated Mon May 11 14:33:35 CEST 2015
     */
    private Long maxValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.SurveyStatus_ID_seq.min_value
     *
     * @mbggenerated Mon May 11 14:33:35 CEST 2015
     */
    private Long minValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.SurveyStatus_ID_seq.cache_value
     *
     * @mbggenerated Mon May 11 14:33:35 CEST 2015
     */
    private Long cacheValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.SurveyStatus_ID_seq.log_cnt
     *
     * @mbggenerated Mon May 11 14:33:35 CEST 2015
     */
    private Long logCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.SurveyStatus_ID_seq.is_cycled
     *
     * @mbggenerated Mon May 11 14:33:35 CEST 2015
     */
    private Boolean isCycled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.SurveyStatus_ID_seq.is_called
     *
     * @mbggenerated Mon May 11 14:33:35 CEST 2015
     */
    private Boolean isCalled;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.SurveyStatus_ID_seq.sequence_name
     *
     * @return the value of public.SurveyStatus_ID_seq.sequence_name
     *
     * @mbggenerated Mon May 11 14:33:35 CEST 2015
     */
    public String getSequenceName() {
        return sequenceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.SurveyStatus_ID_seq.sequence_name
     *
     * @param sequenceName the value for public.SurveyStatus_ID_seq.sequence_name
     *
     * @mbggenerated Mon May 11 14:33:35 CEST 2015
     */
    public void setSequenceName(String sequenceName) {
        this.sequenceName = sequenceName == null ? null : sequenceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.SurveyStatus_ID_seq.last_value
     *
     * @return the value of public.SurveyStatus_ID_seq.last_value
     *
     * @mbggenerated Mon May 11 14:33:35 CEST 2015
     */
    public Long getLastValue() {
        return lastValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.SurveyStatus_ID_seq.last_value
     *
     * @param lastValue the value for public.SurveyStatus_ID_seq.last_value
     *
     * @mbggenerated Mon May 11 14:33:35 CEST 2015
     */
    public void setLastValue(Long lastValue) {
        this.lastValue = lastValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.SurveyStatus_ID_seq.start_value
     *
     * @return the value of public.SurveyStatus_ID_seq.start_value
     *
     * @mbggenerated Mon May 11 14:33:35 CEST 2015
     */
    public Long getStartValue() {
        return startValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.SurveyStatus_ID_seq.start_value
     *
     * @param startValue the value for public.SurveyStatus_ID_seq.start_value
     *
     * @mbggenerated Mon May 11 14:33:35 CEST 2015
     */
    public void setStartValue(Long startValue) {
        this.startValue = startValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.SurveyStatus_ID_seq.increment_by
     *
     * @return the value of public.SurveyStatus_ID_seq.increment_by
     *
     * @mbggenerated Mon May 11 14:33:35 CEST 2015
     */
    public Long getIncrementBy() {
        return incrementBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.SurveyStatus_ID_seq.increment_by
     *
     * @param incrementBy the value for public.SurveyStatus_ID_seq.increment_by
     *
     * @mbggenerated Mon May 11 14:33:35 CEST 2015
     */
    public void setIncrementBy(Long incrementBy) {
        this.incrementBy = incrementBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.SurveyStatus_ID_seq.max_value
     *
     * @return the value of public.SurveyStatus_ID_seq.max_value
     *
     * @mbggenerated Mon May 11 14:33:35 CEST 2015
     */
    public Long getMaxValue() {
        return maxValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.SurveyStatus_ID_seq.max_value
     *
     * @param maxValue the value for public.SurveyStatus_ID_seq.max_value
     *
     * @mbggenerated Mon May 11 14:33:35 CEST 2015
     */
    public void setMaxValue(Long maxValue) {
        this.maxValue = maxValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.SurveyStatus_ID_seq.min_value
     *
     * @return the value of public.SurveyStatus_ID_seq.min_value
     *
     * @mbggenerated Mon May 11 14:33:35 CEST 2015
     */
    public Long getMinValue() {
        return minValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.SurveyStatus_ID_seq.min_value
     *
     * @param minValue the value for public.SurveyStatus_ID_seq.min_value
     *
     * @mbggenerated Mon May 11 14:33:35 CEST 2015
     */
    public void setMinValue(Long minValue) {
        this.minValue = minValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.SurveyStatus_ID_seq.cache_value
     *
     * @return the value of public.SurveyStatus_ID_seq.cache_value
     *
     * @mbggenerated Mon May 11 14:33:35 CEST 2015
     */
    public Long getCacheValue() {
        return cacheValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.SurveyStatus_ID_seq.cache_value
     *
     * @param cacheValue the value for public.SurveyStatus_ID_seq.cache_value
     *
     * @mbggenerated Mon May 11 14:33:35 CEST 2015
     */
    public void setCacheValue(Long cacheValue) {
        this.cacheValue = cacheValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.SurveyStatus_ID_seq.log_cnt
     *
     * @return the value of public.SurveyStatus_ID_seq.log_cnt
     *
     * @mbggenerated Mon May 11 14:33:35 CEST 2015
     */
    public Long getLogCnt() {
        return logCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.SurveyStatus_ID_seq.log_cnt
     *
     * @param logCnt the value for public.SurveyStatus_ID_seq.log_cnt
     *
     * @mbggenerated Mon May 11 14:33:35 CEST 2015
     */
    public void setLogCnt(Long logCnt) {
        this.logCnt = logCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.SurveyStatus_ID_seq.is_cycled
     *
     * @return the value of public.SurveyStatus_ID_seq.is_cycled
     *
     * @mbggenerated Mon May 11 14:33:35 CEST 2015
     */
    public Boolean getIsCycled() {
        return isCycled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.SurveyStatus_ID_seq.is_cycled
     *
     * @param isCycled the value for public.SurveyStatus_ID_seq.is_cycled
     *
     * @mbggenerated Mon May 11 14:33:35 CEST 2015
     */
    public void setIsCycled(Boolean isCycled) {
        this.isCycled = isCycled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.SurveyStatus_ID_seq.is_called
     *
     * @return the value of public.SurveyStatus_ID_seq.is_called
     *
     * @mbggenerated Mon May 11 14:33:35 CEST 2015
     */
    public Boolean getIsCalled() {
        return isCalled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.SurveyStatus_ID_seq.is_called
     *
     * @param isCalled the value for public.SurveyStatus_ID_seq.is_called
     *
     * @mbggenerated Mon May 11 14:33:35 CEST 2015
     */
    public void setIsCalled(Boolean isCalled) {
        this.isCalled = isCalled;
    }
}