package org.fao.fir.cgrfa.dao.mapper.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.fao.fir.cgrfa.dao.mapper.model.Controlledlists;
import org.fao.fir.cgrfa.dao.mapper.model.ControlledlistsExample;

public interface ControlledlistsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ControlledLists
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    long countByExample(ControlledlistsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ControlledLists
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int deleteByExample(ControlledlistsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ControlledLists
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int deleteByPrimaryKey(Integer pk);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ControlledLists
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int insert(Controlledlists record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ControlledLists
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int insertSelective(Controlledlists record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ControlledLists
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    List<Controlledlists> selectByExample(ControlledlistsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ControlledLists
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    Controlledlists selectByPrimaryKey(Integer pk);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ControlledLists
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int updateByExampleSelective(@Param("record") Controlledlists record, @Param("example") ControlledlistsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ControlledLists
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int updateByExample(@Param("record") Controlledlists record, @Param("example") ControlledlistsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ControlledLists
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int updateByPrimaryKeySelective(Controlledlists record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ControlledLists
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int updateByPrimaryKey(Controlledlists record);
}