package org.fao.fir.cgrfa.dao.mapper.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.fao.fir.cgrfa.dao.mapper.model.CountriesInfoNew;
import org.fao.fir.cgrfa.dao.mapper.model.CountriesInfoNewExample;

public interface CountriesInfoNewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Countries_info_new
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    long countByExample(CountriesInfoNewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Countries_info_new
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int deleteByExample(CountriesInfoNewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Countries_info_new
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int deleteByPrimaryKey(Integer uncode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Countries_info_new
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int insert(CountriesInfoNew record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Countries_info_new
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int insertSelective(CountriesInfoNew record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Countries_info_new
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    List<CountriesInfoNew> selectByExample(CountriesInfoNewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Countries_info_new
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    CountriesInfoNew selectByPrimaryKey(Integer uncode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Countries_info_new
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int updateByExampleSelective(@Param("record") CountriesInfoNew record, @Param("example") CountriesInfoNewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Countries_info_new
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int updateByExample(@Param("record") CountriesInfoNew record, @Param("example") CountriesInfoNewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Countries_info_new
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int updateByPrimaryKeySelective(CountriesInfoNew record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Countries_info_new
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int updateByPrimaryKey(CountriesInfoNew record);
}