package org.fao.fir.cgrfa.dao.mapper.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.fao.fir.cgrfa.dao.mapper.model.Fieldlabel;
import org.fao.fir.cgrfa.dao.mapper.model.FieldlabelExample;
import org.fao.fir.cgrfa.dao.mapper.model.FieldlabelKey;

public interface FieldlabelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.FieldLabel
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    long countByExample(FieldlabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.FieldLabel
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int deleteByExample(FieldlabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.FieldLabel
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int deleteByPrimaryKey(FieldlabelKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.FieldLabel
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int insert(Fieldlabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.FieldLabel
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int insertSelective(Fieldlabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.FieldLabel
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    List<Fieldlabel> selectByExample(FieldlabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.FieldLabel
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    Fieldlabel selectByPrimaryKey(FieldlabelKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.FieldLabel
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int updateByExampleSelective(@Param("record") Fieldlabel record, @Param("example") FieldlabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.FieldLabel
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int updateByExample(@Param("record") Fieldlabel record, @Param("example") FieldlabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.FieldLabel
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int updateByPrimaryKeySelective(Fieldlabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.FieldLabel
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int updateByPrimaryKey(Fieldlabel record);
}