package org.fao.fir.cgrfa.dao.mapper.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.fao.fir.cgrfa.dao.mapper.model.Fieldchecklist;
import org.fao.fir.cgrfa.dao.mapper.model.FieldchecklistExample;

public interface FieldchecklistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.FieldCheckList
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    long countByExample(FieldchecklistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.FieldCheckList
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int deleteByExample(FieldchecklistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.FieldCheckList
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.FieldCheckList
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int insert(Fieldchecklist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.FieldCheckList
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int insertSelective(Fieldchecklist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.FieldCheckList
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    List<Fieldchecklist> selectByExample(FieldchecklistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.FieldCheckList
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    Fieldchecklist selectByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.FieldCheckList
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int updateByExampleSelective(@Param("record") Fieldchecklist record, @Param("example") FieldchecklistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.FieldCheckList
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int updateByExample(@Param("record") Fieldchecklist record, @Param("example") FieldchecklistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.FieldCheckList
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int updateByPrimaryKeySelective(Fieldchecklist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.FieldCheckList
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int updateByPrimaryKey(Fieldchecklist record);
}