package org.fao.fir.cgrfa.dao.mapper.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.fao.fir.cgrfa.dao.mapper.model.Q0921PerCountry;
import org.fao.fir.cgrfa.dao.mapper.model.Q0921PerCountryExample;

public interface Q0921PerCountryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Q0921_Per_country
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    long countByExample(Q0921PerCountryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Q0921_Per_country
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int deleteByExample(Q0921PerCountryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Q0921_Per_country
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int insert(Q0921PerCountry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Q0921_Per_country
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int insertSelective(Q0921PerCountry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Q0921_Per_country
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    List<Q0921PerCountry> selectByExample(Q0921PerCountryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Q0921_Per_country
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int updateByExampleSelective(@Param("record") Q0921PerCountry record, @Param("example") Q0921PerCountryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Q0921_Per_country
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int updateByExample(@Param("record") Q0921PerCountry record, @Param("example") Q0921PerCountryExample example);
}