package org.fao.fir.cgrfa.dao.mapper.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.fao.fir.cgrfa.dao.mapper.model.Q0922Percountry;
import org.fao.fir.cgrfa.dao.mapper.model.Q0922PercountryExample;

public interface Q0922PercountryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Q0922_PerCountry
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    long countByExample(Q0922PercountryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Q0922_PerCountry
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int deleteByExample(Q0922PercountryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Q0922_PerCountry
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int insert(Q0922Percountry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Q0922_PerCountry
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int insertSelective(Q0922Percountry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Q0922_PerCountry
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    List<Q0922Percountry> selectByExample(Q0922PercountryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Q0922_PerCountry
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int updateByExampleSelective(@Param("record") Q0922Percountry record, @Param("example") Q0922PercountryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Q0922_PerCountry
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int updateByExample(@Param("record") Q0922Percountry record, @Param("example") Q0922PercountryExample example);
}