package org.fao.fir.cgrfa.dao.mapper.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.fao.fir.cgrfa.dao.mapper.model.Q11flatanswers;
import org.fao.fir.cgrfa.dao.mapper.model.Q11flatanswersExample;

public interface Q11flatanswersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Q11FlatAnswers
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    long countByExample(Q11flatanswersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Q11FlatAnswers
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int deleteByExample(Q11flatanswersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Q11FlatAnswers
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int insert(Q11flatanswers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Q11FlatAnswers
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int insertSelective(Q11flatanswers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Q11FlatAnswers
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    List<Q11flatanswers> selectByExample(Q11flatanswersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Q11FlatAnswers
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int updateByExampleSelective(@Param("record") Q11flatanswers record, @Param("example") Q11flatanswersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Q11FlatAnswers
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int updateByExample(@Param("record") Q11flatanswers record, @Param("example") Q11flatanswersExample example);
}