package org.fao.fir.cgrfa.dao.mapper.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.fao.fir.cgrfa.dao.mapper.model.Question15;
import org.fao.fir.cgrfa.dao.mapper.model.Question15Example;

public interface Question15Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question15
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    long countByExample(Question15Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question15
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int deleteByExample(Question15Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question15
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int insert(Question15 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question15
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int insertSelective(Question15 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question15
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    List<Question15> selectByExample(Question15Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question15
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int updateByExampleSelective(@Param("record") Question15 record, @Param("example") Question15Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question15
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int updateByExample(@Param("record") Question15 record, @Param("example") Question15Example example);
}