package org.fao.fir.cgrfa.dao.mapper.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.fao.fir.cgrfa.dao.mapper.model.Quest44;
import org.fao.fir.cgrfa.dao.mapper.model.Quest44Example;

public interface Quest44Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Quest44
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    long countByExample(Quest44Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Quest44
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    int deleteByExample(Quest44Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Quest44
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    int insert(Quest44 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Quest44
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    int insertSelective(Quest44 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Quest44
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    List<Quest44> selectByExample(Quest44Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Quest44
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    int updateByExampleSelective(@Param("record") Quest44 record, @Param("example") Quest44Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Quest44
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    int updateByExample(@Param("record") Quest44 record, @Param("example") Quest44Example example);
}