package org.fao.fir.cgrfa.dao.mapper.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.fao.fir.cgrfa.dao.mapper.model.Quest50;
import org.fao.fir.cgrfa.dao.mapper.model.Quest50Example;

public interface Quest50Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Quest50
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    long countByExample(Quest50Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Quest50
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    int deleteByExample(Quest50Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Quest50
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    int insert(Quest50 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Quest50
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    int insertSelective(Quest50 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Quest50
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    List<Quest50> selectByExample(Quest50Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Quest50
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    int updateByExampleSelective(@Param("record") Quest50 record, @Param("example") Quest50Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Quest50
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    int updateByExample(@Param("record") Quest50 record, @Param("example") Quest50Example example);
}