package org.fao.fir.cgrfa.dao.mapper.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.fao.fir.cgrfa.dao.mapper.model.Quest29;
import org.fao.fir.cgrfa.dao.mapper.model.Quest29Example;

public interface Quest29Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Quest29
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    long countByExample(Quest29Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Quest29
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    int deleteByExample(Quest29Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Quest29
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    int insert(Quest29 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Quest29
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    int insertSelective(Quest29 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Quest29
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    List<Quest29> selectByExample(Quest29Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Quest29
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    int updateByExampleSelective(@Param("record") Quest29 record, @Param("example") Quest29Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Quest29
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    int updateByExample(@Param("record") Quest29 record, @Param("example") Quest29Example example);
}