package org.fao.fir.cgrfa.dao.mapper.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.fao.fir.cgrfa.dao.mapper.model.Questionstablescolumns;
import org.fao.fir.cgrfa.dao.mapper.model.QuestionstablescolumnsExample;

public interface QuestionstablescolumnsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.QuestionsTablesColumns
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    long countByExample(QuestionstablescolumnsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.QuestionsTablesColumns
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int deleteByExample(QuestionstablescolumnsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.QuestionsTablesColumns
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.QuestionsTablesColumns
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int insert(Questionstablescolumns record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.QuestionsTablesColumns
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int insertSelective(Questionstablescolumns record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.QuestionsTablesColumns
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    List<Questionstablescolumns> selectByExample(QuestionstablescolumnsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.QuestionsTablesColumns
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    Questionstablescolumns selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.QuestionsTablesColumns
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int updateByExampleSelective(@Param("record") Questionstablescolumns record, @Param("example") QuestionstablescolumnsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.QuestionsTablesColumns
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int updateByExample(@Param("record") Questionstablescolumns record, @Param("example") QuestionstablescolumnsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.QuestionsTablesColumns
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int updateByPrimaryKeySelective(Questionstablescolumns record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.QuestionsTablesColumns
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int updateByPrimaryKey(Questionstablescolumns record);
}