package org.fao.fir.cgrfa.dao.mapper.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.fao.fir.cgrfa.dao.mapper.model.QuestionstypePkey;
import org.fao.fir.cgrfa.dao.mapper.model.QuestionstypePkeyExample;

public interface QuestionstypePkeyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.QuestionsType_pkey
     *
     * @mbggenerated Thu May 14 12:52:48 CEST 2015
     */
    int countByExample(QuestionstypePkeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.QuestionsType_pkey
     *
     * @mbggenerated Thu May 14 12:52:48 CEST 2015
     */
    int deleteByExample(QuestionstypePkeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.QuestionsType_pkey
     *
     * @mbggenerated Thu May 14 12:52:48 CEST 2015
     */
    int insert(QuestionstypePkey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.QuestionsType_pkey
     *
     * @mbggenerated Thu May 14 12:52:48 CEST 2015
     */
    int insertSelective(QuestionstypePkey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.QuestionsType_pkey
     *
     * @mbggenerated Thu May 14 12:52:48 CEST 2015
     */
    List<QuestionstypePkey> selectByExample(QuestionstypePkeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.QuestionsType_pkey
     *
     * @mbggenerated Thu May 14 12:52:48 CEST 2015
     */
    int updateByExampleSelective(@Param("record") QuestionstypePkey record, @Param("example") QuestionstypePkeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.QuestionsType_pkey
     *
     * @mbggenerated Thu May 14 12:52:48 CEST 2015
     */
    int updateByExample(@Param("record") QuestionstypePkey record, @Param("example") QuestionstypePkeyExample example);
}