package org.fao.fir.cgrfa.dao.mapper.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.fao.fir.cgrfa.dao.mapper.model.Question31MoreInformation;
import org.fao.fir.cgrfa.dao.mapper.model.Question31MoreInformationExample;

public interface Question31MoreInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question31_more_information
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    long countByExample(Question31MoreInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question31_more_information
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int deleteByExample(Question31MoreInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question31_more_information
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int insert(Question31MoreInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question31_more_information
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int insertSelective(Question31MoreInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question31_more_information
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    List<Question31MoreInformation> selectByExample(Question31MoreInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question31_more_information
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int updateByExampleSelective(@Param("record") Question31MoreInformation record, @Param("example") Question31MoreInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question31_more_information
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int updateByExample(@Param("record") Question31MoreInformation record, @Param("example") Question31MoreInformationExample example);
}