package org.fao.fir.cgrfa.dao.mapper.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.fao.fir.cgrfa.dao.mapper.model.Question48;
import org.fao.fir.cgrfa.dao.mapper.model.Question48Example;

public interface Question48Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question48
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    long countByExample(Question48Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question48
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int deleteByExample(Question48Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question48
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int insert(Question48 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question48
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int insertSelective(Question48 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question48
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    List<Question48> selectByExample(Question48Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question48
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int updateByExampleSelective(@Param("record") Question48 record, @Param("example") Question48Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question48
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int updateByExample(@Param("record") Question48 record, @Param("example") Question48Example example);
}