package org.fao.fir.cgrfa.dao.mapper.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.fao.fir.cgrfa.dao.mapper.model.Questions;
import org.fao.fir.cgrfa.dao.mapper.model.QuestionsExample;

public interface QuestionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Questions
     *
     * @mbggenerated Tue Jun 09 17:34:37 CEST 2015
     */
    int countByExample(QuestionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Questions
     *
     * @mbggenerated Tue Jun 09 17:34:37 CEST 2015
     */
    int deleteByExample(QuestionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Questions
     *
     * @mbggenerated Tue Jun 09 17:34:37 CEST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Questions
     *
     * @mbggenerated Tue Jun 09 17:34:37 CEST 2015
     */
    int insert(Questions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Questions
     *
     * @mbggenerated Tue Jun 09 17:34:37 CEST 2015
     */
    int insertSelective(Questions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Questions
     *
     * @mbggenerated Tue Jun 09 17:34:37 CEST 2015
     */
    List<Questions> selectByExample(QuestionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Questions
     *
     * @mbggenerated Tue Jun 09 17:34:37 CEST 2015
     */
    Questions selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Questions
     *
     * @mbggenerated Tue Jun 09 17:34:37 CEST 2015
     */
    int updateByExampleSelective(@Param("record") Questions record, @Param("example") QuestionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Questions
     *
     * @mbggenerated Tue Jun 09 17:34:37 CEST 2015
     */
    int updateByExample(@Param("record") Questions record, @Param("example") QuestionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Questions
     *
     * @mbggenerated Tue Jun 09 17:34:37 CEST 2015
     */
    int updateByPrimaryKeySelective(Questions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Questions
     *
     * @mbggenerated Tue Jun 09 17:34:37 CEST 2015
     */
    int updateByPrimaryKey(Questions record);
}