package org.fao.fir.cgrfa.dao.mapper.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.fao.fir.cgrfa.dao.mapper.model.Question12;
import org.fao.fir.cgrfa.dao.mapper.model.Question12Example;

public interface Question12Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question12
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    long countByExample(Question12Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question12
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int deleteByExample(Question12Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question12
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int insert(Question12 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question12
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int insertSelective(Question12 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question12
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    List<Question12> selectByExample(Question12Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question12
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int updateByExampleSelective(@Param("record") Question12 record, @Param("example") Question12Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question12
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int updateByExample(@Param("record") Question12 record, @Param("example") Question12Example example);
}