package org.fao.fir.cgrfa.dao.mapper.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.fao.fir.cgrfa.dao.mapper.model.Question42MoreInformation;
import org.fao.fir.cgrfa.dao.mapper.model.Question42MoreInformationExample;

public interface Question42MoreInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question42_more_information
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    long countByExample(Question42MoreInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question42_more_information
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int deleteByExample(Question42MoreInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question42_more_information
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int insert(Question42MoreInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question42_more_information
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int insertSelective(Question42MoreInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question42_more_information
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    List<Question42MoreInformation> selectByExample(Question42MoreInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question42_more_information
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int updateByExampleSelective(@Param("record") Question42MoreInformation record, @Param("example") Question42MoreInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question42_more_information
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int updateByExample(@Param("record") Question42MoreInformation record, @Param("example") Question42MoreInformationExample example);
}