package org.fao.fir.cgrfa.dao.mapper.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.fao.fir.cgrfa.dao.mapper.model.Question16;
import org.fao.fir.cgrfa.dao.mapper.model.Question16Example;

public interface Question16Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question16
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    long countByExample(Question16Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question16
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int deleteByExample(Question16Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question16
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int insert(Question16 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question16
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int insertSelective(Question16 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question16
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    List<Question16> selectByExample(Question16Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question16
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int updateByExampleSelective(@Param("record") Question16 record, @Param("example") Question16Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question16
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int updateByExample(@Param("record") Question16 record, @Param("example") Question16Example example);
}