package org.fao.fir.cgrfa.dao.mapper.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.fao.fir.cgrfa.dao.mapper.model.QuestionstablesrowsPkey;
import org.fao.fir.cgrfa.dao.mapper.model.QuestionstablesrowsPkeyExample;

public interface QuestionstablesrowsPkeyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.QuestionsTablesRows_pkey
     *
     * @mbggenerated Thu May 14 12:52:48 CEST 2015
     */
    int countByExample(QuestionstablesrowsPkeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.QuestionsTablesRows_pkey
     *
     * @mbggenerated Thu May 14 12:52:48 CEST 2015
     */
    int deleteByExample(QuestionstablesrowsPkeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.QuestionsTablesRows_pkey
     *
     * @mbggenerated Thu May 14 12:52:48 CEST 2015
     */
    int insert(QuestionstablesrowsPkey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.QuestionsTablesRows_pkey
     *
     * @mbggenerated Thu May 14 12:52:48 CEST 2015
     */
    int insertSelective(QuestionstablesrowsPkey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.QuestionsTablesRows_pkey
     *
     * @mbggenerated Thu May 14 12:52:48 CEST 2015
     */
    List<QuestionstablesrowsPkey> selectByExample(QuestionstablesrowsPkeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.QuestionsTablesRows_pkey
     *
     * @mbggenerated Thu May 14 12:52:48 CEST 2015
     */
    int updateByExampleSelective(@Param("record") QuestionstablesrowsPkey record, @Param("example") QuestionstablesrowsPkeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.QuestionsTablesRows_pkey
     *
     * @mbggenerated Thu May 14 12:52:48 CEST 2015
     */
    int updateByExample(@Param("record") QuestionstablesrowsPkey record, @Param("example") QuestionstablesrowsPkeyExample example);
}