package org.fao.fir.cgrfa.dao.mapper.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.fao.fir.cgrfa.dao.mapper.model.Questionstables;
import org.fao.fir.cgrfa.dao.mapper.model.QuestionstablesExample;

public interface QuestionstablesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.QuestionsTables
     *
     * @mbggenerated Thu May 14 12:52:48 CEST 2015
     */
    int countByExample(QuestionstablesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.QuestionsTables
     *
     * @mbggenerated Thu May 14 12:52:48 CEST 2015
     */
    int deleteByExample(QuestionstablesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.QuestionsTables
     *
     * @mbggenerated Thu May 14 12:52:48 CEST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.QuestionsTables
     *
     * @mbggenerated Thu May 14 12:52:48 CEST 2015
     */
    int insert(Questionstables record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.QuestionsTables
     *
     * @mbggenerated Thu May 14 12:52:48 CEST 2015
     */
    int insertSelective(Questionstables record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.QuestionsTables
     *
     * @mbggenerated Thu May 14 12:52:48 CEST 2015
     */
    List<Questionstables> selectByExample(QuestionstablesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.QuestionsTables
     *
     * @mbggenerated Thu May 14 12:52:48 CEST 2015
     */
    Questionstables selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.QuestionsTables
     *
     * @mbggenerated Thu May 14 12:52:48 CEST 2015
     */
    int updateByExampleSelective(@Param("record") Questionstables record, @Param("example") QuestionstablesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.QuestionsTables
     *
     * @mbggenerated Thu May 14 12:52:48 CEST 2015
     */
    int updateByExample(@Param("record") Questionstables record, @Param("example") QuestionstablesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.QuestionsTables
     *
     * @mbggenerated Thu May 14 12:52:48 CEST 2015
     */
    int updateByPrimaryKeySelective(Questionstables record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.QuestionsTables
     *
     * @mbggenerated Thu May 14 12:52:48 CEST 2015
     */
    int updateByPrimaryKey(Questionstables record);
}