package org.fao.fir.cgrfa.dao.mapper.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.fao.fir.cgrfa.dao.mapper.model.Question04;
import org.fao.fir.cgrfa.dao.mapper.model.Question04Example;

public interface Question04Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question04
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    long countByExample(Question04Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question04
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int deleteByExample(Question04Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question04
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int insert(Question04 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question04
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int insertSelective(Question04 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question04
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    List<Question04> selectByExample(Question04Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question04
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int updateByExampleSelective(@Param("record") Question04 record, @Param("example") Question04Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question04
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int updateByExample(@Param("record") Question04 record, @Param("example") Question04Example example);
}