package org.fao.fir.cgrfa.dao.mapper.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.fao.fir.cgrfa.dao.mapper.model.Question45;
import org.fao.fir.cgrfa.dao.mapper.model.Question45Example;

public interface Question45Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question45
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    long countByExample(Question45Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question45
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int deleteByExample(Question45Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question45
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int insert(Question45 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question45
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int insertSelective(Question45 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question45
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    List<Question45> selectByExample(Question45Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question45
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int updateByExampleSelective(@Param("record") Question45 record, @Param("example") Question45Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question45
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int updateByExample(@Param("record") Question45 record, @Param("example") Question45Example example);
}