package org.fao.fir.cgrfa.dao.mapper.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.fao.fir.cgrfa.dao.mapper.model.Question32;
import org.fao.fir.cgrfa.dao.mapper.model.Question32Example;

public interface Question32Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question32
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    long countByExample(Question32Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question32
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int deleteByExample(Question32Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question32
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int insert(Question32 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question32
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int insertSelective(Question32 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question32
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    List<Question32> selectByExample(Question32Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question32
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int updateByExampleSelective(@Param("record") Question32 record, @Param("example") Question32Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Question32
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int updateByExample(@Param("record") Question32 record, @Param("example") Question32Example example);
}