package org.fao.fir.cgrfa.dao.mapper.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.fao.fir.cgrfa.dao.mapper.model.Quest05;
import org.fao.fir.cgrfa.dao.mapper.model.Quest05Example;

public interface Quest05Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Quest05
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    long countByExample(Quest05Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Quest05
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    int deleteByExample(Quest05Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Quest05
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    int insert(Quest05 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Quest05
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    int insertSelective(Quest05 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Quest05
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    List<Quest05> selectByExample(Quest05Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Quest05
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    int updateByExampleSelective(@Param("record") Quest05 record, @Param("example") Quest05Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Quest05
     *
     * @mbg.generated Fri Oct 06 16:00:54 CEST 2017
     */
    int updateByExample(@Param("record") Quest05 record, @Param("example") Quest05Example example);
}