package org.fao.fir.cgrfa.dao.mapper.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.fao.fir.cgrfa.dao.mapper.model.Questionstablesrows;
import org.fao.fir.cgrfa.dao.mapper.model.QuestionstablesrowsExample;

public interface QuestionstablesrowsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.QuestionsTablesRows
     *
     * @mbggenerated Thu May 14 12:52:48 CEST 2015
     */
    int countByExample(QuestionstablesrowsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.QuestionsTablesRows
     *
     * @mbggenerated Thu May 14 12:52:48 CEST 2015
     */
    int deleteByExample(QuestionstablesrowsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.QuestionsTablesRows
     *
     * @mbggenerated Thu May 14 12:52:48 CEST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.QuestionsTablesRows
     *
     * @mbggenerated Thu May 14 12:52:48 CEST 2015
     */
    int insert(Questionstablesrows record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.QuestionsTablesRows
     *
     * @mbggenerated Thu May 14 12:52:48 CEST 2015
     */
    int insertSelective(Questionstablesrows record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.QuestionsTablesRows
     *
     * @mbggenerated Thu May 14 12:52:48 CEST 2015
     */
    List<Questionstablesrows> selectByExample(QuestionstablesrowsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.QuestionsTablesRows
     *
     * @mbggenerated Thu May 14 12:52:48 CEST 2015
     */
    Questionstablesrows selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.QuestionsTablesRows
     *
     * @mbggenerated Thu May 14 12:52:48 CEST 2015
     */
    int updateByExampleSelective(@Param("record") Questionstablesrows record, @Param("example") QuestionstablesrowsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.QuestionsTablesRows
     *
     * @mbggenerated Thu May 14 12:52:48 CEST 2015
     */
    int updateByExample(@Param("record") Questionstablesrows record, @Param("example") QuestionstablesrowsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.QuestionsTablesRows
     *
     * @mbggenerated Thu May 14 12:52:48 CEST 2015
     */
    int updateByPrimaryKeySelective(Questionstablesrows record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.QuestionsTablesRows
     *
     * @mbggenerated Thu May 14 12:52:48 CEST 2015
     */
    int updateByPrimaryKey(Questionstablesrows record);
}