package org.fao.fir.cgrfa.dao.mapper.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.fao.fir.cgrfa.dao.mapper.model.Questionstablescolumns;
import org.fao.fir.cgrfa.dao.mapper.model.QuestionstablescolumnsExample;

public interface QuestionstablescolumnsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.QuestionsTablesColumns
     *
     * @mbggenerated Thu May 14 12:52:48 CEST 2015
     */
    int countByExample(QuestionstablescolumnsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.QuestionsTablesColumns
     *
     * @mbggenerated Thu May 14 12:52:48 CEST 2015
     */
    int deleteByExample(QuestionstablescolumnsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.QuestionsTablesColumns
     *
     * @mbggenerated Thu May 14 12:52:48 CEST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.QuestionsTablesColumns
     *
     * @mbggenerated Thu May 14 12:52:48 CEST 2015
     */
    int insert(Questionstablescolumns record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.QuestionsTablesColumns
     *
     * @mbggenerated Thu May 14 12:52:48 CEST 2015
     */
    int insertSelective(Questionstablescolumns record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.QuestionsTablesColumns
     *
     * @mbggenerated Thu May 14 12:52:48 CEST 2015
     */
    List<Questionstablescolumns> selectByExample(QuestionstablescolumnsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.QuestionsTablesColumns
     *
     * @mbggenerated Thu May 14 12:52:48 CEST 2015
     */
    Questionstablescolumns selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.QuestionsTablesColumns
     *
     * @mbggenerated Thu May 14 12:52:48 CEST 2015
     */
    int updateByExampleSelective(@Param("record") Questionstablescolumns record, @Param("example") QuestionstablescolumnsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.QuestionsTablesColumns
     *
     * @mbggenerated Thu May 14 12:52:48 CEST 2015
     */
    int updateByExample(@Param("record") Questionstablescolumns record, @Param("example") QuestionstablescolumnsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.QuestionsTablesColumns
     *
     * @mbggenerated Thu May 14 12:52:48 CEST 2015
     */
    int updateByPrimaryKeySelective(Questionstablescolumns record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.QuestionsTablesColumns
     *
     * @mbggenerated Thu May 14 12:52:48 CEST 2015
     */
    int updateByPrimaryKey(Questionstablescolumns record);
}