package org.fao.fir.cgrfa.dao.mapper.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.fao.fir.cgrfa.dao.mapper.model.SurveyIdSeq;
import org.fao.fir.cgrfa.dao.mapper.model.SurveyIdSeqExample;

public interface SurveyIdSeqMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Survey_ID_seq
     *
     * @mbggenerated Mon May 11 14:33:35 CEST 2015
     */
    int countByExample(SurveyIdSeqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Survey_ID_seq
     *
     * @mbggenerated Mon May 11 14:33:35 CEST 2015
     */
    int deleteByExample(SurveyIdSeqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Survey_ID_seq
     *
     * @mbggenerated Mon May 11 14:33:35 CEST 2015
     */
    int insert(SurveyIdSeq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Survey_ID_seq
     *
     * @mbggenerated Mon May 11 14:33:35 CEST 2015
     */
    int insertSelective(SurveyIdSeq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Survey_ID_seq
     *
     * @mbggenerated Mon May 11 14:33:35 CEST 2015
     */
    List<SurveyIdSeq> selectByExample(SurveyIdSeqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Survey_ID_seq
     *
     * @mbggenerated Mon May 11 14:33:35 CEST 2015
     */
    int updateByExampleSelective(@Param("record") SurveyIdSeq record, @Param("example") SurveyIdSeqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Survey_ID_seq
     *
     * @mbggenerated Mon May 11 14:33:35 CEST 2015
     */
    int updateByExample(@Param("record") SurveyIdSeq record, @Param("example") SurveyIdSeqExample example);
}