package org.fao.fir.cgrfa.dao.mapper.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.fao.fir.cgrfa.dao.mapper.model.Surveyfullanswers;
import org.fao.fir.cgrfa.dao.mapper.model.SurveyfullanswersExample;

public interface SurveyfullanswersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.SurveyFullAnswers
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    long countByExample(SurveyfullanswersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.SurveyFullAnswers
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int deleteByExample(SurveyfullanswersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.SurveyFullAnswers
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int insert(Surveyfullanswers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.SurveyFullAnswers
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int insertSelective(Surveyfullanswers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.SurveyFullAnswers
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    List<Surveyfullanswers> selectByExample(SurveyfullanswersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.SurveyFullAnswers
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int updateByExampleSelective(@Param("record") Surveyfullanswers record, @Param("example") SurveyfullanswersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.SurveyFullAnswers
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int updateByExample(@Param("record") Surveyfullanswers record, @Param("example") SurveyfullanswersExample example);
}