package org.fao.fir.cgrfa.dao.mapper.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.fao.fir.cgrfa.dao.mapper.model.Surveyfieldanswers;
import org.fao.fir.cgrfa.dao.mapper.model.SurveyfieldanswersExample;

public interface SurveyfieldanswersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.SurveyFieldAnswers
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    long countByExample(SurveyfieldanswersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.SurveyFieldAnswers
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int deleteByExample(SurveyfieldanswersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.SurveyFieldAnswers
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int insert(Surveyfieldanswers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.SurveyFieldAnswers
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int insertSelective(Surveyfieldanswers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.SurveyFieldAnswers
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    List<Surveyfieldanswers> selectByExample(SurveyfieldanswersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.SurveyFieldAnswers
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int updateByExampleSelective(@Param("record") Surveyfieldanswers record, @Param("example") SurveyfieldanswersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.SurveyFieldAnswers
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int updateByExample(@Param("record") Surveyfieldanswers record, @Param("example") SurveyfieldanswersExample example);
}