package org.fao.fir.cgrfa.dao.mapper.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.fao.fir.cgrfa.dao.mapper.model.SurveystatusIdSeq;
import org.fao.fir.cgrfa.dao.mapper.model.SurveystatusIdSeqExample;

public interface SurveystatusIdSeqMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.SurveyStatus_ID_seq
     *
     * @mbggenerated Tue Jun 09 17:34:37 CEST 2015
     */
    int countByExample(SurveystatusIdSeqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.SurveyStatus_ID_seq
     *
     * @mbggenerated Tue Jun 09 17:34:37 CEST 2015
     */
    int deleteByExample(SurveystatusIdSeqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.SurveyStatus_ID_seq
     *
     * @mbggenerated Tue Jun 09 17:34:37 CEST 2015
     */
    int insert(SurveystatusIdSeq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.SurveyStatus_ID_seq
     *
     * @mbggenerated Tue Jun 09 17:34:37 CEST 2015
     */
    int insertSelective(SurveystatusIdSeq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.SurveyStatus_ID_seq
     *
     * @mbggenerated Tue Jun 09 17:34:37 CEST 2015
     */
    List<SurveystatusIdSeq> selectByExample(SurveystatusIdSeqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.SurveyStatus_ID_seq
     *
     * @mbggenerated Tue Jun 09 17:34:37 CEST 2015
     */
    int updateByExampleSelective(@Param("record") SurveystatusIdSeq record, @Param("example") SurveystatusIdSeqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.SurveyStatus_ID_seq
     *
     * @mbggenerated Tue Jun 09 17:34:37 CEST 2015
     */
    int updateByExample(@Param("record") SurveystatusIdSeq record, @Param("example") SurveystatusIdSeqExample example);
}