package org.fao.fir.cgrfa.dao.mapper.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.fao.fir.cgrfa.dao.mapper.model.Surveynotdeleted;
import org.fao.fir.cgrfa.dao.mapper.model.SurveynotdeletedExample;

public interface SurveynotdeletedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.SurveyNotDeleted
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    long countByExample(SurveynotdeletedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.SurveyNotDeleted
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int deleteByExample(SurveynotdeletedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.SurveyNotDeleted
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int insert(Surveynotdeleted record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.SurveyNotDeleted
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int insertSelective(Surveynotdeleted record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.SurveyNotDeleted
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    List<Surveynotdeleted> selectByExample(SurveynotdeletedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.SurveyNotDeleted
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int updateByExampleSelective(@Param("record") Surveynotdeleted record, @Param("example") SurveynotdeletedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.SurveyNotDeleted
     *
     * @mbg.generated Tue Oct 10 14:03:47 CEST 2017
     */
    int updateByExample(@Param("record") Surveynotdeleted record, @Param("example") SurveynotdeletedExample example);
}